### ISSUE TITLE
Clipboard: Copying and pasting in documents does not work properly

### ISSUE THREAD

**Issue by Janokisu** [CollaboraOnline/online#12613]
### Describe the Bug
Problem with copy from clipboard to document.

### Steps to Reproduce
1. Copy something to the clipboard (not from the Collabora document)
2. Paste it into the Collabora document using Ctrl + V
3. Nothing was pasted, but something gray was visible for a few milliseconds. I think this is a pop-up message indicating that you should use keyboard shortcuts.
4. Hold down Ctrl + V, then it flickers 3-7 times and then it is pasted
5. It works fine when copying from the Collabora document

### Expected Behavior
Paste, as you know it from all programs.

### Actual Behavior
Nothing is inserted, or insertion is difficult.

### Screenshots

<img width="2124" height="629" alt="Image" src="https://github.com/user-attachments/assets/f1ae8c21-eca2-48fd-b427-b2156bc94996" />

### Additional Context
I used COOL inside Nextcloud
Collabora and Nextcloud run in Docker

HOST: Ubuntu 22.04
Docker: 28.3.3
COOLWSD version: 25.04.4.2
Nextcloud: 31.0.7.1
Nextcloud Office App: 8.7.3

**Comment by jazevedo-coll** [comment]
hi @Janokisu what browser, and browser version you used?

And what do you use for your reverse proxy?

**Comment by Janokisu** [comment]
@jazevedo-coll 
Firefox: 142
Edge: 139

Reverse proxy: nginx/1.29.1

**Comment by ruebezahl17** [comment]
I have here since some weeks the exact same problem!
I can also not insert on my Android phone when editing a document inside the nextcloud app. 
Nextcloud is 31.0.8, Codeserver runs as a Docker container on my Synology (25.04.4.3), the Nextcloud Office app is version 8.7.4. The problem started already with older versions. And it doesn't matter which browser I use (tried Firefox and Chromium on different PCs). And if I press CTRL-V longer than it inserts the text. While pressing the keys the area of the table is flickering.
My reverse proxy is the Synology.

**Comment by iSeeSwift** [comment]
I dont't know if this is the same bug. I am unable to paste anything into text- oder presentation documents (haven't tried anything else).
I use Safari 18.6 on macOS Sequoia 15.6.
I do get a popup that is stating wrong keyboard shortcuts. (Crtl-V instead of Cmd-V, but neither works).

Right now I cannot reproduce the problem. Either it has been fixed since august 19th or it only occurs when copying from a Zoom-Chat in another browser window. (That could offer a workaround by pasting to a different app and copying again) I'll follow up, the next time I am in that situation.

Fwiw the collabora installation is the one that replaced OnlyOffice in wechange.org (that also has a UI that conflicts much less with macOS).

Hope this helps,
ralf

**Comment by henryherkula** [comment]
Same problem. Console outputs this error:

JSDialog: dialog info with id: "modal-dialog-copy_paste_download_progress" not found. proxy.php:29992:61
JSDialog: old data was: {} proxy.php:29993:78
JSDialog: dialog info with id: "modal-dialog-copy_paste_download_progress" not found. proxy.php:29992:61
JSDialog: old data was: {} proxy.php:29993:78

**Comment by Janokisu** [comment]
When this flashes, a new div briefly appears in the HTML structure.
`<div id="modal-dialog-copy_paste_download_progress-overlay" class="jsdialog-overlay dimmed"></div>`

<img width="1386" height="353" alt="Image" src="https://github.com/user-attachments/assets/bbb147be-d02a-4203-a621-1c19baec95e8" />

Is there a way to disable jsdialog-overlay in a config file until the problem is fixed? I think the dialog is blocking the insertion.


If I remove `<div class="jsdialog-overlay dimmed" id="modal-dialog-openlink-overlay"></div>`  from the structure, for example, pasting works without any problems.

Update:
ok, blocking dialog overlay with ublock didn't help

Console outputs on my system this error::
```
JSDialog: dialog info with id: "modal-dialog-copy_paste_download_progress" not found. [bundle.js:29947:61](https://x.y.z/browser/a8848448cc/bundle.js)
JSDialog: old data was: {} [bundle.js:29948:78](https://x.y.z/browser/a8848448cc/bundle.js)
JSDialog: dialog info with id: "modal-dialog-copy_paste_download_progress" not found. [bundle.js:29947:61](https://x.y.z/browser/a8848448cc/bundle.js)
JSDialog: old data was: {} [bundle.js:29948:78](https://x.y.z/browser/a8848448cc/bundle.js)
```

**Comment by nurbi-ka** [comment]
?the same as https://github.com/CollaboraOnline/online/issues/12761#top???

I figured out: Version 25.04.1.1 works fine, 25.04.3.2 and upwards does not, in this versions even the workaround does not work. In (25.04.5.1.1) the funny workaround is to hold Ctrl/V a few seconds. The screen is flickering and after about 3 or 4 seconds the past is done.

**Comment by timur-g** [comment]
Should be fixed with https://github.com/CollaboraOnline/online/pull/12810 . Please try with 25.04.5.2.

**Comment by Janokisu** [comment]
@timur-g the issue is still there. 
But the “modal-dialog-copy_paste_download_progress” issue seems to be gone.

**Comment by ruebezahl17** [comment]
and here it is also the same problem

**Comment by annanazarayan** [comment]
@Janokisu  We’re sorry for the version misunderstanding. The fix was not included in version 25.04.5.2, but it will be available in the next release, 25.04.6.2, which is expected next week.
Thank you for your understanding and support.

**Comment by ruebezahl17** [comment]
It's now more than two weeks and I only got the update to 25.04.5.3 that changed nothing with this problem. When will the mentioned update be available? This problem is really annoying ... 
Thank you.

**Comment by Janokisu** [comment]
I also tested it with 25.04.5.3.1 and the bug is still there.

However, I noticed that when I have the paste window open, pasting in the background works.

<img width="877" height="354" alt="Image" src="https://github.com/user-attachments/assets/72e25407-d53e-40c8-b252-890b3810e2b9" />

**Comment by nurbi-ka** [comment]
The Collabora developers are doing a great job. If you don't absolutely need the modifications in the latest versions, stick with version 25.04.1.1.1 until the fix is released. That version works great!

**Comment by Janokisu** [comment]
@nurbi-ka yes, they are doing a great job. I am just reporting the status.
Until the problem is fixed, I am using version 24.04.13.3.1, because in 25.04.1.1.1, pasting works, but it flickers every time I paste.

**Comment by nurbi-ka** [comment]
agreed, but - for me - it is only a very small, short and almost invisible flicker, nothing like version 25.04.5.1.1, where you have to hold Ctrl/V for 2 seconds and it flickers very intensely before the paste is executed. Is the flickering in version 25.04.1.1.1 severe for you?

**Comment by nurbi-ka** [comment]
and sorry, I forgot to address my comment yesterday to @ruebezahl17

**Comment by Janokisu** [comment]
@nurbi-ka Apology accepted 😉
It's not as bad as the current error, but it is annoying.
Like sporadic lag in video games. You can still play, but it's annoying.

**Comment by Janokisu** [comment]
The issue is still there in 25.04.6.1.1.

**Comment by Ezwen** [comment]
I encounter this problem with Nextcloud `32.0.0` and Collabora `25.04.5.3`.

Copying a text outside the browser, and pasting the text inside Collabora, does not work (nothing happens).

**EDIT**: just tested with Collabora `25.04.6.1`, and unfortunately the problem is still present.

**Comment by nurbi-ka** [comment]
> I encounter this problem with Nextcloud `32.0.0` and Collabora `25.04.5.3`.
> 
> Copying a text outside the browser, and pasting the text inside Collabora, does not work (nothing happens).
> 
> **EDIT**: just tested with Collabora `25.04.6.1`, and unfortunately the problem is still present.

1: are you sure that "nothing happens"? Try to hold Ctrl/V for a few seconds.
2: I am on Nextcloud Hub 10 (31.0.7) with the same issue. This makes clear: it is really a Collabora issue
3: it was announced that it will be fixed with version 25.4.6.2. However, although the rollout was announced about two weeks ago, this version is still not available today.

**Comment by Ezwen** [comment]
> 1: are you sure that "nothing happens"? Try to hold Ctrl/V for a few seconds.

this does work, surprisingly! but it is not very practical as this ends up pasting multiple times

>  3: it was announced that it will be fixed with version 25.4.6.2. However, although the rollout was announced about two weeks ago, this version is still not available today.

good to know, thanks!

**Comment by nurbi-ka** [comment]
@Ezwen 
1: yes, this is true 🤣The trick is to stop (release the buttons) in time 🤣. No, seriously, work with version 25.4.1.1.1, for example (as I do), until it is corrected.

**Comment by nadirlouati** [comment]
not working for version 25.04.6.2 (so revert to working version 25.04.2.1)

COOLWSD version: 25.04.6.2(git hash: eaa2d03190 (E))
LOKit version: Collabora Office 25.04.6.2(git hash: a012111994)
Served by: Debian GNU/Linux 13 (trixie)
Server ID: b94bca76
WOPI host: 


and i have errors on server audit console

<img width="632" height="512" alt="Image" src="https://github.com/user-attachments/assets/838568d3-955e-49f3-bbd6-56e9270f007d" />

i changed my kubernetes deploy and same issue
`
volumeMounts:
            - name: config
              mountPath: /etc/coolwsd/coolwsd.xml
              subPath: coolwsd.xml
            - name: dev-shm
              mountPath: /dev/shm
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              memory: 250Mi
            limits:
              memory: 1000Mi
      volumes:
        - name: config
          configMap:
            name: libreoffice-config
            defaultMode: 420
        - name: dev-shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: tmp
          emptyDir: { }
`

**Comment by Janokisu** [comment]
The issue is still there in 25.04.6.2.1.

**Comment by eszkadev** [comment]
I have fix for some cases of copy paste ongoing: https://github.com/CollaboraOnline/online/pull/13219

The reported issues with "download-progress" like https://github.com/CollaboraOnline/online/issues/12613#issuecomment-3239151317 seems to be in the scope.

In general browsers have limitations around clipboard (https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#security_considerations) so it depends on a setup which code path is used.

**Comment by nurbi-ka** [comment]
@eszkadev 
This appears to be a bug in Collabora and has little to do with limitations. If I install a new version of Collabora in an environment where everything works, and then copy/paste no longer works, and then, still in the same environment, I reinstall an older version of Collabora and everything works, we are not talking about limitations. And if copy/paste works when Ctrl/V is held down for longer than 3 to 4 seconds, what does that have to do with limitations?

**Comment by loftux** [comment]
Tested with 25.04.5.5.1 (latest Collabora Online i could find, docker based), does not work. Tried older versions, but  none of the 25 versions work, reverted to 24.04.9.4.1 and copy and paste works. Unfortunately this version has the older look and feel for the UI.

The error in 25 version is tested with Chrome base browsers, Collabora pops up the dialog telling to use keyboard shortcuts. In the console you will se 
bundle.js:13954 [Violation] Permissions policy violation: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://crbug.com/414348233 for more details.

More details, this is with the Alfresco Share plugin, where Collabora runs in an iframe, and two different domains. Tried all sorts of workarounds such as adding Permissions-Policy header and coolwsd.xml config for wopi and "host allow". No until downgrading version of Collabora did it start to work.

**Comment by tbhagoliwal** [comment]
It is almost 3 months and I am getting used to this handicap. Nothing works, multiple attempts. control insyead of command, after praying, before praying etc. Just nothing happens. no flicker, no blank no text. Is it this big an issue? Is there a combination where it works somewhere in the world.

**Comment by vsessink** [comment]
> It is almost 3 months and I am getting used to this handicap. Nothing works, multiple attempts. control insyead of command, after praying, before praying etc. Just nothing happens. no flicker, no blank no text. Is it this big an issue? Is there a combination where it works somewhere in the world.

https://github.com/CollaboraOnline/online/pull/13242 and https://github.com/CollaboraOnline/richdocumentscode/issues/323 - fix has been merged, waiting for next release.

In the mean time, a workaround exists - use at own risk:
```
sudo -u www-data php /var/www/${NextcloudBaseDirectory}/occ maintenance:mode --on
sudo -u www-data php /var/www/${NextcloudBaseDirectory}/occ app:disable richdocumentscode
cd /var/www/${NextcloudBaseDirectory}/apps/
wget https://github.com/CollaboraOnline/richdocumentscode/releases/download/24.4.1303/richdocumentscode.tar.gz
tar -zxf richdocumentscode.tar.gz 
chown -R www-data:www-data richdocumentscode
sudo -u www-data php /var/www/${NextcloudBaseDirectory}/occ app:enable richdocumentscode
sudo -u www-data php /var/www/${NextcloudBaseDirectory}/occ maintenance:mode --off
```

**Comment by ruebezahl17** [comment]
It works now! Today I updated to 25.04.7.1 and all is fine. Thanks for the work!

**Comment by timur-g** [comment]
Thanks for the check.

**Comment by Janokisu** [comment]
I can confirm that pasting works. 👍

But unfortunately, the flickering is still there.

**Comment by ruebezahl17** [comment]
> I can confirm that pasting works. 👍
> 
> But unfortunately, the flickering is still there.

Here is the flickering no more visible.

**Comment by nurbi-ka** [comment]
> > I can confirm that pasting works. 👍
> > But unfortunately, the flickering is still there.
> 
> Here is the flickering no more visible.

not here either!
And thanks to the developers: I had no time to instal the first version with the fix (25.04.7.1). Now I am on 25.04.7.3. THIS IS THE BEST VERSION EVER - excellent!!! Thanks a lot!

**Comment by canuckdev** [comment]
I have 25.04.7.1, but I still have this problem and see this in the console log:
```
bundle.js:14304 [Violation] Permissions policy violation: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://crbug.com/414348233 for more details.
```
