### ISSUE TITLE
Can't select multiple cells in Writer table in 6.4.3 and 6.4.9 on Android/iOS device

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#2629]
**Description**
Can't select multiple cells in a table on Android smartphone using touch or mouse (6.4.9 on Samsung S8+, Android 9, and a Moto G5). This problem was reported by styxlawyer on the user forum https://forum.collaboraonline.com/t/selecting-multiple-cells-in-writer-table-on-android/417

**To Reproduce**
1. Open Writer document
2. Create a table
3. Using touch or mouse try to select multiple cells, it won't

**Expected behaviour**
Cells to be highlighted.

**Actual behaviour**
Nothing happens.

**Additional context**
Note - It is possible to select multiple cells in a table on a Chromebook using the keyboard or trackpad or mouse, but not when using touch as can't drag the pear shaped selectors? (6.4.3 on Chromebook X360)

**Comment by Ezinnem** [comment]
I can reproduce this on Andriod 10.

**Comment by nikslor** [comment]
This is also an issue on iOS, I hope it's okay to reflect that also in the title?

**Comment by thebearon** [comment]
> This is also an issue on iOS, I hope it's okay to reflect that also in the title?

Absolutely, thanks for the additional triaging, @nikslor!

**Comment by nikslor** [comment]
It's now possible to select multiple cells (vertically and horizontally) using the iOS app 22.05.11 (22.5.202303212054).
Maybe this is fixed in Android as well?

**Comment by Darshan-upadhyay1110** [comment]
This is still reproducible.
> It's now possible to select multiple cells (vertically and horizontally) using the iOS app 22.05.11 (22.5.202303212054). Maybe this is fixed in Android as well?
 But i think as per last comment it is working for IOS

CC: @Ezinnem @jazevedo-coll @timur-g

**Comment by timur-g** [comment]
Not sure. I can select multiple cells in Android 21.11 and also in 24.04 snapshot. Of course, in edit mode.
But, it is not straightforward, it may take some time to select 1st cell content and get tear-drops, then to draw tear-drops and get cells selected. Or may fail.

So, we can select multiple cells, this may be WorksForMe, but really it should be better.
I would like to be able to select row or column by simple click on square marks outside (where we resize rows and columns).
