### ISSUE TITLE
CODE 6.4.10 - Well, this is embarrassing

### ISSUE THREAD

**Issue by manu-p** [CollaboraOnline/online#2771]
**Describe the bug**
Since 6.4.10, the message "Well, this is embarrassing..." has appeared on an remote instance that had been working fine for a long time before.
Configuration:
NC instance "cloud.NC-**client**" running NC 20.0.6 and Collabora 3.8.3 using a CODE server named "code.NC-**server**" (below).

NC instance "cloud.NC-**server**" running NC 20.0.6 and Collabora 3.8.3 and CODE in a docker, the same code.NC-server.

Since latest 6.4.10 everything keeps working fine on NC-server, CODE is opening odt, ods, docx, ... files as it did before. 
But on NC-client, CODE is not opening files anymore as it did before. The message "Well, this is embarrassing..." is displayed instead.

I managed to revert to the previous 6.4.9 image in docker on NC-server and everything's working fine again on NC-client and NC-server.

**Comment by thebearon** [comment]
Can you share what errors the CODE docker logs show when you try opening a file?

**Comment by manu-p** [comment]
Hi @thebearon thanks.

Not easy, unless I can find old docker logs somewhere ?
My browser tells me yesterday I've been looking for:
`ERR Socket #36 SSL BIO error: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error (0: Success)| ./net/SslSocket.hpp`
and
`ERR Socket #22 SSL BIO error: closed unexpectedly (-1). (0: Success)| ./net/SslSocket.hpp:294`
which were amongst the 1st ERR messages I could find in "docker logs -f"

The NC-server is running Ubuntu 18.04 with nginx 1.14. 
Docker version 20.10.7, build f0df350
The subdomain code.NC-server has its own LetsEncrypt certificate which I forced to renew, in case.

At last, I reverted all nginx and loolwds.xml files back to their previous setups which used to work fine before friday and, as said before, managed to revert to CODE 6.4.9 image in docker.

These two servers are production servers, I can't play too much with their setup.

**Comment by stavros-k** [comment]
```
Ready to accept connections on port 9980.

wsd-00007-00045 2021-07-09 19:36:27.117439 [ websrv_poll ] WRN client - server version mismatch, disabling browser cache. Expected: 2c4ce99| wsd/FileServer.cpp:288

wsd-00007-00045 2021-07-09 19:36:27.117834 [ websrv_poll ] WRN Skipping the token [--co-primary-text= rgba(252, 252, 252, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117847 [ websrv_poll ] WRN Skipping the token [--co-primary-element= rgba(61, 174, 233, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117853 [ websrv_poll ] WRN Skipping the token [--co-text-accent= rgba(61, 174, 233, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117861 [ websrv_poll ] WRN Skipping the token [--co-primary-element-light= rgba(61, 174, 233, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117867 [ websrv_poll ] WRN Skipping the token [--co-color-error= rgba(218, 68, 83, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144

wsd-00007-00045 2021-07-09 19:36:27.117876 [ websrv_poll ] WRN Skipping the token [--co-color-warning= rgba(246, 116, 0, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144

wsd-00007-00045 2021-07-09 19:36:27.117884 [ websrv_poll ] WRN Skipping the token [--co-color-success= rgba(39, 174, 96, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117888 [ websrv_poll ] WRN Skipping the token [--co-border-radius= 3px] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117893 [ websrv_poll ] WRN Skipping the token [--co-border-radius-large= 10px] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117902 [ websrv_poll ] WRN Skipping the token [--co-loading-light= rgba(189, 195, 199, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117910 [ websrv_poll ] WRN Skipping the token [--co-loading-dark= rgba(127, 140, 141, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117919 [ websrv_poll ] WRN Skipping the token [--co-box-shadow= rgba(0, 0, 0, 0) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117925 [ websrv_poll ] WRN Skipping the token [--co-border= rgba(103, 107, 110, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117932 [ websrv_poll ] WRN Skipping the token [--co-border-dark= rgba(103, 107, 110, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117939 [ websrv_poll ] WRN Skipping the token [--co-border-radius-pill= 100px] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00047 2021-07-09 19:36:27.346635 [ docbroker_001 ] WRN Waking up dead poll thread [HttpSynReqPoll], started: false, finished: false| ./net/Socket.hpp:673
wsd-00007-00047 2021-07-09 19:36:27.346839 [ docbroker_001 ] ERR Socket #31 SSL BIO error: closed unexpectedly (-1). (0: Success)| ./net/SslSocket.hpp:294

wsd-00007-00047 2021-07-09 19:36:27.346920 [ docbroker_001 ] ERR Error while handling poll for socket #31 in HttpSynReqPoll: SSL Socket closed unexpectedly.| net/Socket.cpp:356

wsd-00007-00047 2021-07-09 19:36:27.346999 [ docbroker_001 ] ERR WOPI::CheckFileInfo failed for URI [https://cloud.DOMAIN.me/index.php/apps/richdocuments/wopi/files/1202030_NCHASH?access_token=TOKEN&access_token_ttl=0]: 0 . Headers: Body: []| wsd/Storage.cpp:723

wsd-00007-00047 2021-07-09 19:36:27.347063 [ docbroker_001 ] ERR loading document exception: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:1854

wsd-00007-00047 2021-07-09 19:36:27.347088 [ docbroker_001 ] ERR Failed to add session to [/index.php/apps/richdocuments/wopi/files/1202030_NCHASH] with URI [https://cloud.DOMAIN.me/index.php/apps/richdocuments/wopi/files/1202030_NCHASH?access_token=TOKEN&access_token_ttl=0]: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:1816

wsd-00007-00047 2021-07-09 19:36:27.347220 [ docbroker_001 ] ERR #26: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1255
wsd-00007-00047 2021-07-09 19:36:27.347237 [ docbroker_001 ] ERR Invalid or unknown session [002] to remove.| wsd/DocumentBroker.cpp:1893
wsd-00007-00045 2021-07-09 19:36:27.117439 [ websrv_poll ] WRN client - server version mismatch, disabling browser cache. Expected: 2c4ce99| wsd/FileServer.cpp:288

wsd-00007-00045 2021-07-09 19:36:27.117834 [ websrv_poll ] WRN Skipping the token [--co-primary-text= rgba(252, 252, 252, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117847 [ websrv_poll ] WRN Skipping the token [--co-primary-element= rgba(61, 174, 233, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117853 [ websrv_poll ] WRN Skipping the token [--co-text-accent= rgba(61, 174, 233, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117861 [ websrv_poll ] WRN Skipping the token [--co-primary-element-light= rgba(61, 174, 233, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117867 [ websrv_poll ] WRN Skipping the token [--co-color-error= rgba(218, 68, 83, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144

wsd-00007-00045 2021-07-09 19:36:27.117876 [ websrv_poll ] WRN Skipping the token [--co-color-warning= rgba(246, 116, 0, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144

wsd-00007-00045 2021-07-09 19:36:27.117884 [ websrv_poll ] WRN Skipping the token [--co-color-success= rgba(39, 174, 96, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117888 [ websrv_poll ] WRN Skipping the token [--co-border-radius= 3px] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117893 [ websrv_poll ] WRN Skipping the token [--co-border-radius-large= 10px] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117902 [ websrv_poll ] WRN Skipping the token [--co-loading-light= rgba(189, 195, 199, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117910 [ websrv_poll ] WRN Skipping the token [--co-loading-dark= rgba(127, 140, 141, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117919 [ websrv_poll ] WRN Skipping the token [--co-box-shadow= rgba(0, 0, 0, 0) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117925 [ websrv_poll ] WRN Skipping the token [--co-border= rgba(103, 107, 110, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117932 [ websrv_poll ] WRN Skipping the token [--co-border-dark= rgba(103, 107, 110, 1) ] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00045 2021-07-09 19:36:27.117939 [ websrv_poll ] WRN Skipping the token [--co-border-radius-pill= 100px] since it contains forbidden characters| wsd/FileServerUtil.cpp:144
wsd-00007-00047 2021-07-09 19:36:27.346635 [ docbroker_001 ] WRN Waking up dead poll thread [HttpSynReqPoll], started: false, finished: false| ./net/Socket.hpp:673
wsd-00007-00047 2021-07-09 19:36:27.346839 [ docbroker_001 ] ERR Socket #31 SSL BIO error: closed unexpectedly (-1). (0: Success)| ./net/SslSocket.hpp:294

wsd-00007-00047 2021-07-09 19:36:27.346920 [ docbroker_001 ] ERR Error while handling poll for socket #31 in HttpSynReqPoll: SSL Socket closed unexpectedly.| net/Socket.cpp:356

wsd-00007-00047 2021-07-09 19:36:27.346999 [ docbroker_001 ] ERR WOPI::CheckFileInfo failed for URI [https://cloud.DOMAIN.me/index.php/apps/richdocuments/wopi/files/1202030_NCHASH?access_token=TOKEN&access_token_ttl=0]: 0 . Headers: Body: []| wsd/Storage.cpp:723

wsd-00007-00047 2021-07-09 19:36:27.347063 [ docbroker_001 ] ERR loading document exception: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:1854

wsd-00007-00047 2021-07-09 19:36:27.347088 [ docbroker_001 ] ERR Failed to add session to [/index.php/apps/richdocuments/wopi/files/1202030_NCHASH] with URI [https://cloud.DOMAIN.me/index.php/apps/richdocuments/wopi/files/1202030_NCHASH?access_token=TOKEN&access_token_ttl=0]: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:1816

wsd-00007-00047 2021-07-09 19:36:27.347220 [ docbroker_001 ] ERR #26: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1255
wsd-00007-00047 2021-07-09 19:36:27.347237 [ docbroker_001 ] ERR Invalid or unknown session [002] to remove.| wsd/DocumentBroker.cpp:1893
wsd-00007-00045 2021-07-09 19:36:28.072133 [ websrv_poll ] WRN DocBroker with docKey [/index.php/apps/richdocuments/wopi/files/1202030_NCHASH] that is marked to be destroyed. Rejecting client request.| wsd/LOOLWSD.cpp:2144
wsd-00007-00045 2021-07-09 19:36:28.072256 [ websrv_poll ] ERR Error while handling Client WS Request: Failed to create DocBroker with docKey [/index.php/apps/richdocuments/wopi/files/1202030_NCHASH].| wsd/LOOLWSD.cpp:3613

wsd-00007-00045 2021-07-09 19:36:28.072278 [ websrv_poll ] ERR #30: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1255
wsd-00007-00045 2021-07-09 19:36:28.072308 [ websrv_poll ] ERR #30: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1255
wsd-00007-00045 2021-07-09 19:36:28.072316 [ websrv_poll ] WRN Socket #30 is shutting down but 64 bytes couldn't be flushed and still remain in the output buffer.| ./net/WebSocketHandler.hpp:764
wsd-00007-00045 2021-07-09 19:36:28.072328 [ websrv_poll ] ERR #30: attempted to remove: 943 which is > size: 0 clamped to 0| ./net/Socket.hpp:1091
wsd-00007-00045 2021-07-09 19:36:28.072344 [ websrv_poll ] ERR #30: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1255
wsd-00007-00045 2021-07-09 19:36:29.202041 [ websrv_poll ] WRN DocBroker with docKey [/index.php/apps/richdocuments/wopi/files/1202030_NCHASH] that is marked to be destroyed. Rejecting client request.| wsd/LOOLWSD.cpp:2144
wsd-00007-00045 2021-07-09 19:36:29.202136 [ websrv_poll ] ERR Error while handling Client WS Request: Failed to create DocBroker with docKey [/index.php/apps/richdocuments/wopi/files/1202030_NCHASH].| wsd/LOOLWSD.cpp:3613

wsd-00007-00045 2021-07-09 19:36:29.202152 [ websrv_poll ] ERR #30: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1255
wsd-00007-00045 2021-07-09 19:36:29.202171 [ websrv_poll ] ERR #30: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1255
wsd-00007-00045 2021-07-09 19:36:29.202179 [ websrv_poll ] WRN Socket #30 is shutting down but 64 bytes couldn't be flushed and still remain in the output buffer.| ./net/WebSocketHandler.hpp:764
wsd-00007-00045 2021-07-09 19:36:29.202190 [ websrv_poll ] ERR #30: attempted to remove: 943 which is > size: 0 clamped to 0| ./net/Socket.hpp:1091
wsd-00007-00045 2021-07-09 19:36:29.202204 [ websrv_poll ] ERR #30: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1255
wsd-00007-00040 2021-07-09 19:36:29.347621 [ prisoner_poll ] WRN Prisoner connection disconnected but without valid socket.| wsd/LOOLWSD.cpp:2231
wsd-00007-00049 2021-07-09 19:36:30.321809 [ docbroker_002 ] WRN Waking up dead poll thread [HttpSynReqPoll], started: false, finished: false| ./net/Socket.hpp:673
wsd-00007-00049 2021-07-09 19:36:30.322022 [ docbroker_002 ] ERR Socket #31 SSL BIO error: closed unexpectedly (-1). (0: Success)| ./net/SslSocket.hpp:294

wsd-00007-00049 2021-07-09 19:36:30.322091 [ docbroker_002 ] ERR Error while handling poll for socket #31 in HttpSynReqPoll: SSL Socket closed unexpectedly.| net/Socket.cpp:356

wsd-00007-00049 2021-07-09 19:36:30.322164 [ docbroker_002 ] ERR WOPI::CheckFileInfo failed for URI [https://cloud.DOMAIN.me/index.php/apps/richdocuments/wopi/files/1202030_NCHASH?access_token=TOKEN&access_token_ttl=0&permission=edit]: 0 . Headers: Body: []| wsd/Storage.cpp:723

wsd-00007-00049 2021-07-09 19:36:30.322238 [ docbroker_002 ] ERR loading document exception: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:1854

wsd-00007-00049 2021-07-09 19:36:30.322265 [ docbroker_002 ] ERR Failed to add session to [/index.php/apps/richdocuments/wopi/files/1202030_NCHASH] with URI [https://cloud.DOMAIN.me/index.php/apps/richdocuments/wopi/files/1202030_NCHASH?access_token=TOKEN&access_token_ttl=0&permission=edit]: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:1816

wsd-00007-00049 2021-07-09 19:36:30.322443 [ docbroker_002 ] ERR #22: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1255
wsd-00007-00049 2021-07-09 19:36:30.322481 [ docbroker_002 ] ERR Invalid or unknown session [005] to remove.| wsd/DocumentBroker.cpp:1893
wsd-00007-00049 2021-07-09 19:36:30.321809 [ docbroker_002 ] WRN Waking up dead poll thread [HttpSynReqPoll], started: false, finished: false| ./net/Socket.hpp:673
wsd-00007-00049 2021-07-09 19:36:30.322022 [ docbroker_002 ] ERR Socket #31 SSL BIO error: closed unexpectedly (-1). (0: Success)| ./net/SslSocket.hpp:294

wsd-00007-00049 2021-07-09 19:36:30.322091 [ docbroker_002 ] ERR Error while handling poll for socket #31 in HttpSynReqPoll: SSL Socket closed unexpectedly.| net/Socket.cpp:356

wsd-00007-00049 2021-07-09 19:36:30.322164 [ docbroker_002 ] ERR WOPI::CheckFileInfo failed for URI [https://cloud.DOMAIN.me/index.php/apps/richdocuments/wopi/files/1202030_NCHASH?access_token=TOKEN&access_token_ttl=0&permission=edit]: 0 . Headers: Body: []| wsd/Storage.cpp:723

wsd-00007-00049 2021-07-09 19:36:30.322238 [ docbroker_002 ] ERR loading document exception: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:1854

wsd-00007-00049 2021-07-09 19:36:30.322265 [ docbroker_002 ] ERR Failed to add session to [/index.php/apps/richdocuments/wopi/files/1202030_NCHASH] with URI [https://cloud.DOMAIN.me/index.php/apps/richdocuments/wopi/files/1202030_NCHASH?access_token=TOKEN&access_token_ttl=0&permission=edit]: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:1816

wsd-00007-00049 2021-07-09 19:36:30.322443 [ docbroker_002 ] ERR #22: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1255
wsd-00007-00049 2021-07-09 19:36:30.322481 [ docbroker_002 ] ERR Invalid or unknown session [005] to remove.| wsd/DocumentBroker.cpp:1893
wsd-00007-00040 2021-07-09 19:36:32.322553 [ prisoner_poll ] WRN Prisoner connection disconnected but without valid socket.| wsd/LOOLWSD.cpp:2231
wsd-00007-00063 2021-07-09 19:36:38.603152 [ docbroker_003 ] WRN Waking up dead poll thread [HttpSynReqPoll], started: false, finished: false| ./net/Socket.hpp:673
wsd-00007-00063 2021-07-09 19:36:38.603467 [ docbroker_003 ] ERR Socket #31 SSL BIO error: closed unexpectedly (-1). (0: Success)| ./net/SslSocket.hpp:294

wsd-00007-00063 2021-07-09 19:36:38.603513 [ docbroker_003 ] ERR Error while handling poll for socket #31 in HttpSynReqPoll: SSL Socket closed unexpectedly.| net/Socket.cpp:356

wsd-00007-00063 2021-07-09 19:36:38.603563 [ docbroker_003 ] ERR WOPI::CheckFileInfo failed for URI [https://cloud.DOMAIN.me/index.php/apps/richdocuments/wopi/files/1202030_NCHASH?access_token=TOKEN&access_token_ttl=0&permission=edit]: 0 . Headers: Body: []| wsd/Storage.cpp:723

wsd-00007-00063 2021-07-09 19:36:38.603607 [ docbroker_003 ] ERR loading document exception: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:1854

wsd-00007-00063 2021-07-09 19:36:38.603622 [ docbroker_003 ] ERR Failed to add session to [/index.php/apps/richdocuments/wopi/files/1202030_NCHASH] with URI [https://cloud.DOMAIN.me/index.php/apps/richdocuments/wopi/files/1202030_NCHASH?access_token=TOKEN&access_token_ttl=0&permission=edit]: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:1816

wsd-00007-00063 2021-07-09 19:36:38.603700 [ docbroker_003 ] ERR #23: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1255
wsd-00007-00063 2021-07-09 19:36:38.603713 [ docbroker_003 ] ERR Invalid or unknown session [006] to remove.| wsd/DocumentBroker.cpp:1893
wsd-00007-00040 2021-07-09 19:36:40.604008 [ prisoner_poll ] WRN Prisoner connection disconnected but without valid socket.| wsd/LOOLWSD.cpp:2231
```
CODE Docker image 6.4.10.3
NC 21.0.3  - LSIO Docker Image
Collabora NC APP - 4.2.0
NginxProxyManager - points to http://collaboradocker:9980, websocket support enabled, lets encrypt ssl with http/2 support also enabled.
Docker command: `docker run -d --name='Collabora' --net='bridge' --privileged=true -e TZ="Europe/Athens" -e HOST_OS="Unraid" -e 'domain'='cloud\.DOMAIN\.me' -e 'username'='admin' -e 'password'='tV9n8akuRXgv' -e 'server_name'='collabora\.DOMAIN\.me' -e 'dictionaries'='en_US el_GR' -e 'extra_params'='-o:welcome.enable=false -o:user_interface.mode=notebookbar -o:ssl.enable=false -o:ssl.termination=true' -p '9980:9980/tcp' -v '/etc/localtime':'/etc/localtime':'ro' 'collabora/code:6.4.10.3'`

When i revert to `6.4.9.3` everything works.

**Comment by Debianer** [comment]
I made a post in the Collabora forum, which refered me to this Github bug:

https://forum.collaboraonline.com/t/code-6-4-10-docker-nextcloud-not-working/440/8

I run Nextcloud as well as CODE in seperate LXD containers on Ubuntu 20.04 and haven't had issues with this for the past three years. CODE comes from the package installation. All containers can be reached from one proxy container which also terminates ssl. It runs haproxy, but I can switch to Apache or Nginx, if that helps. The CODE LXD container has it's own URL and SSL on the proxy. So it's NextcloudURL.com and CODEurl.com. 

When I upgraded last week, CODE broke. I can't really pin the error in the logs, as there are so many error messages and I don't know which one is the original error. 

If someone shows me how I can revert to an earlier version using the linux packages I can do that and test if that solves the problem. A reinstall of a new 20.04 container in a 20.04 LXD host and haproxy environment yields the same results. CODE is broken for Nextcloud for me.

**Comment by Debianer** [comment]
@stavros-k

Thanks for the tip. Do you know a source for 6.4.9 packages? They only seem to have the very latest packages in the repository and in usually do the apt clean command which empties the package cache on the local machine. Do you recommend I should stop doing that for CODE? Is this expected to happen more often in the future? 

https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu2004/

Does anyone know where the issue is located? Is this because of the Nextcloud integration? Or is it related to the proxy?

**Comment by stavros-k** [comment]
> @stavros-k
> 
> Thanks for the tip. Do you know a source for 6.4.9 packages? They only seem to have the very latest packages in the repository and in usually do the apt clean command which empties the package cache on the local machine. Do you recommend I should stop doing that for CODE? Is this expected to happen more often in the future? 
> 
> https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu2004/
> 
> Does anyone know where the issue is located? Is this because of the Nextcloud integration? Or is it related to the proxy? 

I'm not really sure how they structure their repo..
But I would keep the last 2 locally.
Over the last year I'm using code, I personally only had this problem occurred once, but was quickly fixed in less than a day.
But this now is something I can't explain.
It's 4 or more images (accounting the removed and overwritten ones) which for at least some people are broken. And github/forum posts have zero activity for solutions or workarounds.

**Comment by manu-p** [comment]
@Debianer 

> Do you know a source for 6.4.9 packages? 

I think I reverted back to 6.4.9 using this command:
`docker pull collabora/code@sha256:e137c4b62205d4d176cf4bec2f208e441bca8dbddf5200d076648d706d1ecb07`

I no longer automatically update CODE as I used to, until I'm sure someone has solved this issue.

**Comment by lle** [comment]
Like manu-p, I also had to revert back to 6.4.9. I'm running Collabora+Nextcloud dockers on Unraid.
I'm definitely following this thread. Looking forward to hear more.

**Comment by stavros-k** [comment]
`6.4.10.5` STILL NOT WORKING. 
It's either something changed and not documented, or all people in this ticket cannot find it.
OR this is some kind of joke...
I cannot believe that after 5 images (or more if we count the overwrites/deletes) still there is no working image.

**Comment by ironicx** [comment]
Summary: 
I believe this issue is caused by the loolwsd http client not sending a SNI parameter during the TLS handshake.
I experienced the same issue since 6.4.10 up to 6.4.10.5
A work around is to disable "SSLStrictSNIVHostCheck" in the Apache configuration of the nextcloud instance (or similiar option for other web servers).

Long version:
I'm running the CODE debian packages in a lxc container together with nextcloud 21.0.3 in an apache reverse proxy configuration (ssl.enable = false, ssl.termination = true)
The system was working fine, but no documents can be opened since CODE update to 6.4.10. Error message "Well, this is embarrassing..." 

From the attached trace log, it can be seen that the loolwsd process makes a https request to the nextcloud server before fetching the document. And this https request fails due to missing SNI.

There is no error when I used wget in the CODE container to get the same URL:
```
root@test:~# wget -S 'https://test.virtualfreedom.de/mcloud/index.php/apps/richdocuments/wopi/files/3303_ocbyi3v7bsd8?access_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&access_token_ttl=0&permission=edit'
--2021-07-21 01:27:23--  https://test.virtualfreedom.de/mcloud/index.php/apps/richdocuments/wopi/files/3303_ocbyi3v7bsd8?access_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&access_token_ttl=0&permission=edit
Resolving test.virtualfreedom.de (test.virtualfreedom.de)... 192.x.x.x
Connecting to test.virtualfreedom.de (test.virtualfreedom.de)|192.x.x.x|:443... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Date: Tue, 20 Jul 2021 23:27:24 GMT
  Server: Apache
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  Referrer-Policy: no-referrer
  X-Content-Type-Options: nosniff
  X-Download-Options: noopen
  X-Frame-Options: SAMEORIGIN
  X-Permitted-Cross-Domain-Policies: none
  X-Robots-Tag: none
  X-XSS-Protection: 1; mode=block
  Upgrade: h2
  Connection: Upgrade, Keep-Alive
  Set-Cookie: ocbyi3v7bsd8=XXXX; path=/mcloud; secure; HttpOnly; SameSite=Lax                                                                                              
  Expires: Thu, 19 Nov 1981 08:52:00 GMT
  Cache-Control: no-cache, no-store, must-revalidate
  Pragma: no-cache
  Set-Cookie: oc_sessionPassphrase=XXXX; path=/mcloud; secure; HttpOnly; SameSite=Lax
  Set-Cookie: ocbyi3v7bsd8=XXXX; path=/mcloud; secure; HttpOnly; SameSite=Lax                                                                                              
  Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'                                                                                         
  Set-Cookie: nc_sameSiteCookielax=true; path=/mcloud; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax                                                                      
  Set-Cookie: nc_sameSiteCookiestrict=true; path=/mcloud; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict                                                                
  Feature-Policy: autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'                                                                            
  Content-Length: 651
  Keep-Alive: timeout=5, max=100
  Content-Type: application/json; charset=utf-8
Length: 651 [application/json]
Saving to: ‘3303_ocbyi3v7bsd8?access_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&access_token_ttl=0&permission=edit’                                                                                  

3303_ocbyi3v7bsd8?access_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 100%[========================================================================================================>]     651  --.-KB/s    in 0s      

2021-07-21 01:27:24 (16.6 MB/s) - ‘3303_ocbyi3v7bsd8?access_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&access_token_ttl=0&permission=edit’ saved [651/651]                                           
```

My  nextcloud instance runs on an apache server that is configured for TLS 1.2 and 1.3 only and included   "SSLStrictSNIVHostCheck On" in the ocnfiguration. After disabling this option and restarting apache, document are loaded again in nextcloud.


[loolwsd_trace_log.txt](https://github.com/CollaboraOnline/online/files/6851827/loolwsd_trace_log.txt)

**Comment by eszkadev** [comment]
It's the duplicate bugreport of https://github.com/CollaboraOnline/online/issues/2752
as disabling "SSLStrictSNIVHostCheck" helps. Fix is ongoing: https://github.com/CollaboraOnline/online/pull/2925

**Comment by manu-p** [comment]
This ticket may have been closed, but I'll wait for someone to confirm it is actually solved in a future CODE release... Until then, I'll stick with 6.4.9 because on a production instance we're not playing this game...

**Comment by stavros-k** [comment]
Ticket is closed because it's duplicate, and the duplicate is still open.
PR is still open for the fix.
Both links are in the previous comment 😉

**Comment by jacotec** [comment]
This is *not* yet fully solved. Also with 6.4.10-10 my NC instances still do not work. The log always shows

`... Socket #xx has times out while requesting [GET .....]`

when Collabora wants to download the document from the Nextcloud server. Manually calling the same link in the browser works, and also in the Collabora log the NC server returns code 200 which is fine.

Reverting to 6.4.9.x and everything immediately works in the same environment.

That should be reopened.

**Comment by palto42** [comment]
I just upgraded to Collabora docker 6.4.13.2 and it still doesn't work well with NC 22.2.0. Have to stay on 6.4.11.3 which works without issues.



Have to stay on old version 6.4.11.3 :(

**Comment by nagi1** [comment]
Confirmed i'm in 6.4.13.3 and it's not working at all!

**Comment by jacotec** [comment]
> It's working for me. I don't think it's related with this. 

Confirmed. No issues with that build, must be something different.

**Comment by HumanG33k** [comment]
hi, 

I have kind of same issue for me it can be a network issue. 
For what i try following things impact the issue : 

- the hostname : declaring the office.domain.tld in /etc/hosts change the behavior 
- the order of the ip version may impact too (as say in the conffile.xml)
- may be related but no clue for now the ssl configuration off the nextcloud. 
- if the public ip is not the server ip (nat behind firewall for ie)

It can explain : why some external nextcloud instance can reach collabora but not the host. 

Not sure i post a the right place but who knows maybe it can help to solve that.
