### ISSUE TITLE
CODE 6.4.10: Mouse pointer slips away from scrollbar.

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#2789]
**Describe the bug**
The mouse pointer can distance itself from the scrollbar when scrolling, this occurs for both the horizontal and vertical scrollbars, This is reproducible on Writer and Calc. Scrollbars do not appear in Impress and Draw. Neither of these will prevent me from doing my work.

**Reproduce the bug**
- Writer and Calc - There are 2 methods to reproduce the mouse-scrollbar slippage:

Method 1
1. Open a file that is perhaps 10 pages long (or wide).
2. Using the mouse, drag the scrollbar down very quickly, repeat down through the file.

Method 2
1. Open a file that is perhaps 10 pages long (or wide).
2. Go down a few pages.
2. Whilst dragging the scrollbar with the mouse jiggle the mouse up and down quickly.

- Impress and Draw - To demonstrate the lack of scrollbar
1. Create a few pages until a scrollbar appears.
2. ~1 second after the scrollbar appears it disappears and will not appear again.

**Expected behaviour**
Writer and Calc: I would expect the mouse pointer to remain with the scrollbar. It behaves properly in CODE 6.4.2 and on a Chromebook with Collabora Office App 6.4.3, so a regression.
Impress and Draw: I would expect the scrollbar to be accessible.  A scrollbar appears and works correctly in Impress in Collabora Office 6.4.3 on a Chromebook, I could not test in earlier CODE, but based on the CODE based Chromebook app it looks like a regression.

**Actual behaviour**
Writer and Calc: When using the vertical scrollbar, the mouse pointer slips down lower than the scrollbar.
Impress and Draw: No longer a scrollbar.

**Desktop (please complete the following information)**
 - Chromebook, Google Chrome Version 91.0.4472.114 (Official Build) (64-bit)
 - LOOLWSD 6.4.10snapshot (git hash: 94a1a06) Served by: 492fe155 (Commits on Jul 5, 2021), LOKit Collabora Office 6.4-43 (git hash: 6fc051b)

**Additional context**
I am based in Australia and the CODE server I am testing is in the UK, increased latency may create or exacerbate issues that may not otherwise be apparent.

**Comment by kendy** [comment]
@gokaysatir: Indeed, this is annoying - can you please have a look?  Thank you!

**Comment by gokaysatir** [comment]
Thank you very much for this detailed report:)
    I couldn't reproduce the problem. We have some new improvements on scroll bars. There was a bug which was causing the scroll bars behave buggy on files with multiple pages. That bug is solved and probably the behaviour you explained has also changed in a good way.
Version 6.4.10-6 is now ready, maybe you can give it a try :)

**Comment by rpear** [comment]
Mostly fixed, but still not like 6.4.2:  Tested on a Chromebook with a recent upgrade 6.4.10snapshot (git hash: b4fa48ef  - this gives me a 404 error).  

1:  OK now:  Mouse pointer slips away from scrollbar for a multi page file, when dragging the scrollbar down _very_ quickly, repeating this down through the file.
2:  OK now:  Mouse pointer slips away from scrollbar for a multi page file, when dragging the scrollbar jiggle the mouse up and down quickly.
3:  Mouse pointer slips away from scrollbar, when dragging the scrollbar above or below the page.  
Opinion: This does not feel as buggy as the other 2, so perhaps less important.
See video for a 6.4.2 vs 6.4.10 comparison: https://user-images.githubusercontent.com/80790599/127414059-3e757918-4928-479d-b1fe-c0becb2baa48.mp4

**Comment by gokaysatir** [comment]
Hello,
The 3rd issue is also solved i think :)

**Comment by rpear** [comment]
All of the above issues are now fixed for me. Thank you for your hard work!

Tested using  COOLWSD version: 21.11.0.2snapshot git hash:  c95afc5 LOKit version: built on a great technology base Collabora Office 21.06.6.1 git hash:  12bda3a Ubuntu 18.04.6 LTS

**Comment by gokaysatir** [comment]
Thank you for the great feedback :) Let's close this issue :)
