### ISSUE TITLE
process charsh with SIGABRT on ARM64

### ISSUE THREAD

**Issue by jkumeboshi** [CollaboraOnline/online#3736]
I've just updated from docker image 6.4.14.3 (e7f48130566c) to "latest" tag (21.11.0.3 -> 92420bb36400) and some process crashed with SIGABRT

I'm using meson64 kernel (Hardkernel ODROID N2):
Armbian 21.08.6 Buster with Linux 5.10.60-meson64

I'm switching back to 6.4.14.3 image

this is the crash log:

```
collabora    | Server: COOLWSD HTTP Server 21.11.0.3
collabora    | Upgrade: websocket
collabora    | Connection: Upgrade
collabora    | Sec-WebSocket-Accept: 4VMQ5GhR4q1WbtXz2AXZPCqspII=
collabora    | | ./net/WebSocketHandler.hpp:867
collabora    | wsd-00001-00030 2021-11-28 17:59:49.779083 +0000 [ prisoner_poll ] TRC  #20: Wrote outgoing data 201 bytes of 201 buffered bytes (ENOENT: No such file or directory)| ./net/Socket.hpp:1372
collabora    | wsd-00001-00030 2021-11-28 17:59:49.779128 +0000 [ prisoner_poll ] INF  ChildProcess ctor [33].| wsd/COOLWSD.hpp:58
collabora    | wsd-00001-00030 2021-11-28 17:59:49.779158 +0000 [ prisoner_poll ] DBG  #20 resetting thread affinity while in transit (was 0xffff9d1ac0c0)| ./net/Socket.hpp:325
collabora    | wsd-00001-00030 2021-11-28 17:59:49.779181 +0000 [ prisoner_poll ] TRC  Calling addNewChild in disposition's move thing to add to NewChildren| wsd/COOLWSD.cpp:2474
collabora    | wsd-00001-00030 2021-11-28 17:59:49.779201 +0000 [ prisoner_poll ] TRC  Adding one child to NewChildren| wsd/COOLWSD.cpp:515
collabora    | wsd-00001-00030 2021-11-28 17:59:49.779218 +0000 [ prisoner_poll ] INF  Have 1 spare child after adding [33].| wsd/COOLWSD.cpp:519
collabora    | wsd-00001-00030 2021-11-28 17:59:49.779238 +0000 [ prisoner_poll ] TRC  Notifying NewChildrenCV| wsd/COOLWSD.cpp:522
collabora    | wsd-00001-00030 2021-11-28 17:59:49.779304 +0000 [ prisoner_poll ] DBG  Removing socket #20 (at 2 of 3) from prisoner_poll| net/Socket.cpp:490
collabora    | wsd-00001-00001 2021-11-28 17:59:49.779326 +0000 [ coolwsd ] TRC  Have 1 new children.| wsd/COOLWSD.cpp:4252
collabora    | wsd-00001-00001 2021-11-28 17:59:49.779454 +0000 [ coolwsd ] INF  WSD initialization complete: setting log-level to [warning] as configured.| wsd/COOLWSD.cpp:4268
collabora    | Ready to accept connections on port 9980.
collabora    |
collabora    | kit-00033-00031 2021-11-28 18:00:04.279690 +0000 [ kit_spare_001 ] SIG   Fatal signal received: SIGABRT
collabora    | Backtrace 33 - { "ProductName": "Collabora Office", "ProductVersion": "21.06", "ProductExtension": ".8.1", "BuildId": "68738ca6d632ed57ea25bc8909959bad0d171872" }:
collabora    | /usr/bin/coolforkit(_ZN7SigUtil13dumpBacktraceEv+0x80)[0xaaaabf1daf60]
collabora    | /usr/bin/coolforkit(+0x1ebc48)[0xaaaabf1dbc48]
collabora    | linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0xffff953287d8]
collabora    | /lib/aarch64-linux-gnu/libc.so.6(raise+0xb0)[0xffff94c914f8]
collabora    | frk-00031-00031 2021-11-28 18:00:04.882030 +0000 [ forkit ] WRN  No live Kits exist, and we are not terminating yet.| kit/ForKit.cpp:293
collabora    | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora    | frk-00031-00031 2021-11-28 18:00:04.894440 +0000 [ forkit ] ERR  Failed to unmount [/opt/cool/child-roots/K1wSjUX6yVmeJ1e6/tmp]| common/JailUtil.cpp:70
collabora    | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora    | frk-00031-00031 2021-11-28 18:00:04.904243 +0000 [ forkit ] ERR  Failed to unmount [/opt/cool/child-roots/K1wSjUX6yVmeJ1e6/lo]| common/JailUtil.cpp:70
collabora    | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora    | frk-00031-00031 2021-11-28 18:00:04.914053 +0000 [ forkit ] ERR  Failed to unmount [/opt/cool/child-roots/K1wSjUX6yVmeJ1e6]| common/JailUtil.cpp:70
collabora    | wsd-00001-00030 2021-11-28 18:00:09.799950 +0000 [ prisoner_poll ] WRN  Removing dead spare child [33].| wsd/COOLWSD.cpp:448
collabora    | wsd-00001-00030 2021-11-28 18:00:09.800075 +0000 [ prisoner_poll ] WRN  Prisoner connection disconnected but without valid socket.| wsd/COOLWSD.cpp:2363
collabora    | kit-00043-00031 2021-11-28 18:00:31.345056 +0000 [ kit_spare_002 ] SIG   Fatal signal received: SIGABRT
collabora    | Backtrace 43 - kit startup of 21.11.0.3 b5534c4cc:
collabora    | /usr/bin/coolforkit(_ZN7SigUtil13dumpBacktraceEv+0x80)[0xaaaabf1daf60]
collabora    | /usr/bin/coolforkit(+0x1ebc48)[0xaaaabf1dbc48]
collabora    | linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0xffff953287d8]
collabora    | /lib/aarch64-linux-gnu/libc.so.6(raise+0xb0)[0xffff94c914f8]
collabora    | frk-00031-00031 2021-11-28 18:00:31.875494 +0000 [ forkit ] WRN  No live Kits exist, and we are not terminating yet.| kit/ForKit.cpp:293
collabora    | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora    | frk-00031-00031 2021-11-28 18:00:31.888622 +0000 [ forkit ] ERR  Failed to unmount [/opt/cool/child-roots/DjtjB30NC8AQuRir/tmp]| common/JailUtil.cpp:70
collabora    | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora    | frk-00031-00031 2021-11-28 18:00:31.910469 +0000 [ forkit ] ERR  Failed to unmount [/opt/cool/child-roots/DjtjB30NC8AQuRir/lo]| common/JailUtil.cpp:70
collabora    | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora    | frk-00031-00031 2021-11-28 18:00:31.932367 +0000 [ forkit ] ERR  Failed to unmount [/opt/cool/child-roots/DjtjB30NC8AQuRir]| common/JailUtil.cpp:70

```

I was using following customized config file form 6.4 image:

```
<!-- -*- nxml-child-indent: 4; tab-width: 4; indent-tabs-mode: nil -*- -->
<config>

    <!-- For more detailed documentation on typical configuration options please see:
         https://sdk.collaboraonline.com/docs/installation/Configuration.html -->

    <!-- Note: 'default' attributes are used to document a setting's default value as well as to use as fallback. -->
    <!-- Note: When adding a new entry, a default must be set in WSD in case the entry is missing upon deployment. -->

    <allowed_languages desc="List of supported languages of Writing Aids (spell checker, grammar checker, thesaurus, hyphenation) on this instance. Allowing too many has negative effect on startup performance." default="de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru">de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru</allowed_languages>

    <sys_template_path desc="Path to a template tree with shared libraries etc to be used as source for chroot jails for child processes." type="path" relative="true" default="systemplate"></sys_template_path>
    <child_root_path desc="Path to the directory under which the chroot jails for the child processes will be created. Should be on the same file system as systemplate and lotemplate. Must be an empty directory." type="path" relative="true" default="jails"></child_root_path>
    <mount_jail_tree desc="Controls whether the systemplate and lotemplate contents are mounted or not, which is much faster than the default of linking/copying each file." type="bool" default="true"></mount_jail_tree>

    <server_name desc="External hostname:port of the server running loolwsd. If empty, it's derived from the request (please set it if this doesn't work). Must be specified when behind a reverse-proxy or when the hostname is not reachable directly." type="string" default=""></server_name>
    <file_server_root_path desc="Path to the directory that should be considered root for the file server. This should be the directory containing loleaflet." type="path" relative="true" default="loleaflet/../"></file_server_root_path>
    <hexify_embedded_urls desc="Enable to protect encoded URLs from getting decoded by intermediate hops. Particularly useful on Azure deployments" type="bool" default="false"></hexify_embedded_urls>

    <memproportion desc="The maximum percentage of system memory consumed by all of the Collabora Online Development Edition, after which we start cleaning up idle documents" type="double" default="80.0"></memproportion>
    <num_prespawn_children desc="Number of child processes to keep started in advance and waiting for new clients." type="uint" default="1">1</num_prespawn_children>
    <per_document desc="Document-specific settings, including LO Core settings.">
        <max_concurrency desc="The maximum number of threads to use while processing a document." type="uint" default="4">4</max_concurrency>
        <batch_priority desc="A (lower) priority for use by batch eg. convert-to processes to avoid starving interactive ones" type="uint" default="5">5</batch_priority>
        <document_signing_url desc="The endpoint URL of signing server, if empty the document signing is disabled" type="string" default=""></document_signing_url>
        <redlining_as_comments desc="If true show red-lines as comments" type="bool" default="false">false</redlining_as_comments>
        <pdf_resolution_dpi desc="The resolution, in DPI, used to render PDF documents as image. Memory consumption grows proportionally. Must be a positive value less than 385. Defaults to 96." type="uint" default="96">96</pdf_resolution_dpi>
        <idle_timeout_secs desc="The maximum number of seconds before unloading an idle document. Defaults to 1 hour." type="uint" default="3600">3600</idle_timeout_secs>
        <!-- Idle save and auto save are checked every 30 seconds -->
        <!-- They are disabled when the value is zero or negative. -->
        <idlesave_duration_secs desc="The number of idle seconds after which document, if modified, should be saved. Defaults to 30 seconds." type="int" default="30">30</idlesave_duration_secs>
        <autosave_duration_secs desc="The number of seconds after which document, if modified, should be saved. Defaults to 5 minutes." type="int" default="300">300</autosave_duration_secs>
        <always_save_on_exit desc="On exiting the last editor, always perform the save, even if the document is not modified." type="bool" default="false">false</always_save_on_exit>
        <limit_virt_mem_mb desc="The maximum virtual memory allowed to each document process. 0 for unlimited." type="uint">0</limit_virt_mem_mb>
        <limit_stack_mem_kb desc="The maximum stack size allowed to each document process. 0 for unlimited." type="uint">8000</limit_stack_mem_kb>
        <limit_file_size_mb desc="The maximum file size allowed to each document process to write. 0 for unlimited." type="uint">0</limit_file_size_mb>
        <limit_num_open_files desc="The maximum number of files allowed to each document process to open. 0 for unlimited." type="uint">0</limit_num_open_files>
        <limit_load_secs desc="Maximum number of seconds to wait for a document load to succeed. 0 for unlimited." type="uint" default="100">100</limit_load_secs>
        <limit_convert_secs desc="Maximum number of seconds to wait for a document conversion to succeed. 0 for unlimited." type="uint" default="100">100</limit_convert_secs>
        <cleanup desc="Checks for resource consuming (bad) documents and kills associated kit process. A document is considered resource consuming (bad) if is in idle state for idle_time_secs period and memory usage passed limit_dirty_mem_mb or CPU usage passed limit_cpu_per" enable="false">
            <cleanup_interval_ms desc="Interval between two checks" type="uint" default="10000">10000</cleanup_interval_ms>
            <bad_behavior_period_secs desc="Minimum time period for a document to be in bad state before associated kit process is killed. If in this period the condition for bad document is not met once then this period is reset" type="uint" default="60">60</bad_behavior_period_secs>
            <idle_time_secs desc="Minimum idle time for a document to be candidate for bad state" type="uint" default="300">300</idle_time_secs>
            <limit_dirty_mem_mb desc="Minimum memory usage for a document to be candidate for bad state" type="uint" default="3072">3072</limit_dirty_mem_mb>
            <limit_cpu_per desc="Minimum CPU usage for a document to be candidate for bad state" type="uint" default="85">85</limit_cpu_per>
            <lost_kit_grace_period_secs desc="The minimum grace period for a lost kit process (not referenced by loolwsd) to resolve its lost status before it is terminated. To disable the cleanup of lost kits use value 0" default="120">120</lost_kit_grace_period_secs>
        </cleanup>
    </per_document>

    <per_view desc="View-specific settings.">
        <out_of_focus_timeout_secs desc="The maximum number of seconds before dimming and stopping updates when the browser tab is no longer in focus. Defaults to 120 seconds." type="uint" default="120">120</out_of_focus_timeout_secs>
        <idle_timeout_secs desc="The maximum number of seconds before dimming and stopping updates when the user is no longer active (even if the browser is in focus). Defaults to 15 minutes." type="uint" default="900">900</idle_timeout_secs>
    </per_view>

    <loleaflet_html desc="Allows UI customization by replacing the single endpoint of loleaflet.html" type="string" default="loleaflet.html">loleaflet.html</loleaflet_html>

    <logging>
        <color type="bool">true</color>
        <level type="string" desc="Can be 0-8 (with the lowest numbers being the least verbose), or none (turns off logging), fatal, critical, error, warning, notice, information, debug, trace" default="warning">warning</level>
        <most_verbose_level_settable_from_client type="string" desc="A loggingleveloverride message from the client can not set a more verbose log level than this" default="notice">notice</most_verbose_level_settable_from_client>
        <least_verbose_level_settable_from_client type="string" desc="A loggingleveloverride message from a client can not set a less verbose log level than this" default="fatal">fatal</least_verbose_level_settable_from_client>
        <protocol type="bool" desc="Enable minimal client-site JS protocol logging from the start">false</protocol>
        <!-- lokit_sal_log example: Log WebDAV-related messages, that is interesting for debugging Insert - Image operation: "+TIMESTAMP+INFO.ucb.ucp.webdav+WARN.ucb.ucp.webdav"
             See also: https://docs.libreoffice.org/sal/html/sal_log.html -->
        <lokit_sal_log type="string" desc="Fine tune log messages from LOKit. Default is to suppress log messages from LOKit." default="-INFO-WARN">-INFO-WARN</lokit_sal_log>
        <file enable="false">
            <!-- If you use other path than /var/log and you run loolwsd from systemd, make sure that you enable that path in loolwsd.service (ReadWritePaths). -->
            <property name="path" desc="Log file path.">/var/log/loolwsd.log</property>
            <property name="rotation" desc="Log file rotation strategy. See Poco FileChannel.">never</property>
            <property name="archive" desc="Append either timestamp or number to the archived log filename.">timestamp</property>
            <property name="compress" desc="Enable/disable log file compression.">true</property>
            <property name="purgeAge" desc="The maximum age of log files to preserve. See Poco FileChannel.">10 days</property>
            <property name="purgeCount" desc="The maximum number of log archives to preserve. Use 'none' to disable purging. See Poco FileChannel.">10</property>
            <property name="rotateOnOpen" desc="Enable/disable log file rotation on opening.">true</property>
            <property name="flush" desc="Enable/disable flushing after logging each line. May harm performance. Note that without flushing after each line, the log lines from the different processes will not appear in chronological order.">false</property>
        </file>
        <anonymize>
            <anonymize_user_data type="bool" desc="Enable to anonymize/obfuscate of user-data in logs. If default is true, it was forced at compile-time and cannot be disabled." default="false">false</anonymize_user_data>
            <anonymization_salt type="uint" desc="The salt used to anonymize/obfuscate user-data in logs. Use a secret 64-bit random number." default="82589933">82589933</anonymization_salt>
        </anonymize>
    </logging>

    <trace_event desc="The possibility to turn on generation of a Chrome Trace Event file" enable="false">
        <path desc="Output path for the Trace Event file, to which they will be written if turned on at run-time" type="string" default="/var/log/loolwsd.trace.json">/var/log/loolwsd.trace.json</path>
    </trace_event>

    <loleaflet_logging desc="Logging in the browser console" default="false">false</loleaflet_logging>

    <trace desc="Dump commands and notifications for replay. When 'snapshot' is true, the source file is copied to the path first." enable="false">
        <path desc="Output path to hold trace file and docs. Use '%' for timestamp to avoid overwriting. For example: /some/path/to/looltrace-%.gz" compress="true" snapshot="false"></path>
        <filter>
            <message desc="Regex pattern of messages to exclude"></message>
        </filter>
        <outgoing>
            <record desc="Whether or not to record outgoing messages" default="false">false</record>
        </outgoing>
    </trace>

    <net desc="Network settings">
      <!-- On systems where localhost resolves to IPv6 [::1] address first, when net.proto is all and net.listen is loopback, loolwsd unexpectedly listens on [::1] only.
           You need to change net.proto to IPv4, if you want to use 127.0.0.1. -->
      <proto type="string" default="all" desc="Protocol to use IPv4, IPv6 or all for both">all</proto>
      <listen type="string" default="any" desc="Listen address that loolwsd binds to. Can be 'any' or 'loopback'.">any</listen>
      <!-- this allows you to shift all of our URLs into a sub-path from
           https://my.com/loleaflet/a123... to https://my.com/my/sub/path/loleaflet/a123... -->
      <service_root type="path" default="" desc="Prefix all the pages, websockets, etc. with this path."></service_root>
      <post_allow desc="Allow/deny client IP address for POST(REST)." allow="true">
        <host desc="any.">[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}</host>
        <host desc="The IPv4 private 192.168 block as plain IPv4 dotted decimal addresses.">192\.168\.[0-9]{1,3}\.[0-9]{1,3}</host>
        <host desc="Ditto, but as IPv4-mapped IPv6 addresses">::ffff:192\.168\.[0-9]{1,3}\.[0-9]{1,3}</host>
        <host desc="The IPv4 loopback (localhost) address.">127\.0\.0\.1</host>
        <host desc="Ditto, but as IPv4-mapped IPv6 address">::ffff:127\.0\.0\.1</host>
        <host desc="The IPv6 loopback (localhost) address.">::1</host>
        <host desc="The IPv4 private 172.17.0.0/16 subnet (Docker).">172\.17\.[0-9]{1,3}\.[0-9]{1,3}</host>
        <host desc="Ditto, but as IPv4-mapped IPv6 addresses">::ffff:172\.17\.[0-9]{1,3}\.[0-9]{1,3}</host>
      </post_allow>
      <frame_ancestors desc="Specify who is allowed to embed the LO Online iframe (loolwsd and WOPI host are always allowed). Separate multiple hosts by space."></frame_ancestors>
      <connection_timeout_secs desc="Specifies the connection, send, recv timeout in seconds for connections initiated by loolwsd (such as WOPI connections)." type="int" default="30"></connection_timeout_secs>

      <!-- this setting radically changes how online works, it should not be used in a production environment -->
      <proxy_prefix type="bool" default="false" desc="Enable a ProxyPrefix to be passed int through which to redirect requests"></proxy_prefix>
    </net>

    <ssl desc="SSL settings">
        <!-- switches from https:// + wss:// to http:// + ws:// -->
        <enable type="bool" desc="Controls whether SSL encryption between loolwsd and the network is enabled (do not disable for production deployment). If default is false, must first be compiled with SSL support to enable." default="true">true</enable>
        <!-- SSL off-load can be done in a proxy, if so disable SSL, and enable termination below in production -->
        <termination desc="Connection via proxy where loolwsd acts as working via https, but actually uses http." type="bool" default="true">true</termination>
        <cert_file_path desc="Path to the cert file" relative="false">/etc/loolwsd/cert.pem</cert_file_path>
        <key_file_path desc="Path to the key file" relative="false">/etc/loolwsd/key.pem</key_file_path>
        <ca_file_path desc="Path to the ca file" relative="false">/etc/loolwsd/ca-chain.cert.pem</ca_file_path>
        <cipher_list desc="List of OpenSSL ciphers to accept" default="ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH"></cipher_list>
        <hpkp desc="Enable HTTP Public key pinning" enable="false" report_only="false">
            <max_age desc="HPKP's max-age directive - time in seconds browser should remember the pins" enable="true">1000</max_age>
            <report_uri desc="HPKP's report-uri directive - pin validation failure are reported at this URL" enable="false"></report_uri>
            <pins desc="Base64 encoded SPKI fingerprints of keys to be pinned">
            <pin></pin>
            </pins>
        </hpkp>
    </ssl>

    <security desc="Altering these defaults potentially opens you to significant risk">
      <seccomp desc="Should we use the seccomp system call filtering." type="bool" default="true">true</seccomp>
      <capabilities desc="Should we require capabilities to isolate processes into chroot jails" type="bool" default="true">true</capabilities>
      <jwt_expiry_secs desc="Time in seconds before the Admin Console's JWT token expires" type="int" default="1800">1800</jwt_expiry_secs>
      <enable_macros_execution desc="Specifies whether the macro execution is enabled in general. This will enable Basic, Beanshell, Javascript and Python scripts. If it is set to false, the macro_security_level is ignored. If it is set to true, the mentioned entry specified the level of macro security." type="bool" default="false">false</enable_macros_execution>
      <macro_security_level desc="Level of Macro security. 1 (Medium) Confirmation required before executing macros from untrusted sources. 0 (Low, not recommended) All macros will be executed without confirmation." type="int" default="1">1</macro_security_level>
    </security>

    <watermark>
      <opacity desc="Opacity of on-screen watermark from 0.0 to 1.0" type="double" default="0.2"></opacity>
      <text desc="Watermark text to be displayed on the document if entered" type="string"></text>
    </watermark>

    <welcome>
      <enable type="bool" desc="Controls whether the welcome screen should be shown to the users on new install and updates." default="true">true</enable>
      <enable_button type="bool" desc="Controls whether the welcome screen should have an explanatory button instead of an X button to close the dialog." default="false">false</enable_button>
      <path desc="Path to 'welcome-$lang.html' files served on first start or when the version changes. When empty, defaults to the Release notes." type="path" relative="true" default="loleaflet/welcome"></path>
    </welcome>

    <user_interface>
      <mode type="string" desc="Controls the user interface style (classic|notebookbar)" default="classic">classic</mode>
    </user_interface>

    <storage desc="Backend storage">
        <filesystem allow="false" />
        <wopi desc="Allow/deny wopi storage. Mutually exclusive with webdav." allow="true">
            <host desc="Regex pattern of hostname to allow or deny." allow="true">cloud\.example\.com</host>
            <host desc="Regex pattern of hostname to allow or deny." allow="true">sf\.example\.com</host>
            <host desc="Regex pattern of hostname to allow or deny." allow="true">10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}</host>
            <host desc="Regex pattern of hostname to allow or deny." allow="true">172\.1[6789]\.[0-9]{1,3}\.[0-9]{1,3}</host>
            <host desc="Regex pattern of hostname to allow or deny." allow="true">172\.2[0-9]\.[0-9]{1,3}\.[0-9]{1,3}</host>
            <host desc="Regex pattern of hostname to allow or deny." allow="true">172\.3[01]\.[0-9]{1,3}\.[0-9]{1,3}</host>
            <host desc="Regex pattern of hostname to allow or deny." allow="false">192\.168\.1\.1</host>
            <max_file_size desc="Maximum document size in bytes to load. 0 for unlimited." type="uint">0</max_file_size>
            <reuse_cookies desc="When enabled, cookies from the browser will be captured and set on WOPI requests." type="bool" default="false">false</reuse_cookies>
            <locking desc="Locking settings">
                <refresh desc="How frequently we should re-acquire a lock with the storage server, in seconds (default 15 mins) or 0 for no refresh" type="int" default="900">900</refresh>
            </locking>
        </wopi>
        <ssl desc="SSL settings">
	    <as_scheme type="bool" default="true" desc="When set we exclusively use the WOPI URI's scheme to enable SSL for storage">true</as_scheme>
            <enable type="bool" desc="If as_scheme is false or not set, this can be set to force SSL encryption between storage and loolwsd. When empty this defaults to following the ssl.enable setting"></enable>
            <cert_file_path desc="Path to the cert file" relative="false"></cert_file_path>
            <key_file_path desc="Path to the key file" relative="false"></key_file_path>
            <ca_file_path desc="Path to the ca file. If this is not empty, then SSL verification will be strict, otherwise cert of storage (WOPI-like host) will not be verified." relative="false"></ca_file_path>
            <cipher_list desc="List of OpenSSL ciphers to accept. If empty the defaults are used. These can be overriden only if absolutely needed."></cipher_list>
        </ssl>
    </storage>

    <tile_cache_persistent desc="Should the tiles persist between two editing sessions of the given document?" type="bool" default="true">true</tile_cache_persistent>

    <admin_console desc="Web admin console settings.">
        <enable desc="Enable the admin console functionality" type="bool" default="true">true</enable>
        <enable_pam desc="Enable admin user authentication with PAM" type="bool" default="false">false</enable_pam>
        <username desc="The username of the admin console. Ignored if PAM is enabled.">admin</username>
        <password desc="The password of the admin console. Deprecated on most platforms. Instead, use PAM or loolconfig to set up a secure password.">spa1000lam</password>
    </admin_console>

    <monitors desc="Addresses of servers we connect to on start for monitoring">
    </monitors>

    

</config>

```

**Comment by GeorgeWells** [comment]
The newly released version (21.11.0.4.1) looks to be working for me.

**Comment by jkumeboshi** [comment]
I've just updated to following version, and it just works as v6.4:

COOLWSD version: 21.11.0.5
git hash:  15dc78e4

**Comment by Ezinnem** [comment]
Closing this issue as it has been resolved.

**Comment by ElaaxMarketing** [comment]
I also have this bug
bar unfortunately I can go back to version 6.4.0.2 and it still doesn't work

`root@mail:/home/dbauer# docker logs COLLABORAOFFICE | grep "ERR"
wsd-00001-00001 2021-12-06 13:38:36.705024 +0000 [ coolwsd ] ERR  Failed to unmount [/opt/cool/child-roots/]| common/JailUtil.cpp:70
wsd-00001-00001 2021-12-06 13:38:36.706591 +0000 [ coolwsd ] ERR  Failed to bind-mount [/opt/cool/systemplate] -> [/opt/cool/child-roots/cool_test_mount].| common/JailUtil.cpp:47
wsd-00001-00001 2021-12-06 13:38:36.706629 +0000 [ coolwsd ] ERR  Bind-Mounting fails and will be disabled for this run. To disable permanently set mount_jail_tree config entry in coolwsd.xml to false.| common/JailUtil.cpp:209
wsd-00001-00001 2021-12-06 13:38:37.510543 +0000 [ coolwsd ] ERR  Failed to open directory [/usr/bin/browser/welcome] (ENOENT: No such file or directory)| wsd/FileServer.cpp:737
wsd-00001-00001 2021-12-06 13:38:37.519474 +0000 [ coolwsd ] ERR  #18 Bind to location coolwsd-RGIFm7oI result - 0 (ENOENT: No such file or directory)| net/Socket.cpp:1005
wsd-00001-00001 2021-12-06 13:43:16.251359 +0000 [ coolwsd ] ERR  Failed to unmount [/opt/cool/child-roots/X1XOTa7GEOp8hcxu/tmp]| common/JailUtil.cpp:70
wsd-00001-00001 2021-12-06 13:43:16.255361 +0000 [ coolwsd ] ERR  Failed to unmount [/opt/cool/child-roots/X1XOTa7GEOp8hcxu/lo]| common/JailUtil.cpp:70
wsd-00001-00001 2021-12-06 13:43:16.258785 +0000 [ coolwsd ] ERR  Failed to unmount [/opt/cool/child-roots/X1XOTa7GEOp8hcxu]| common/JailUtil.cpp:70
wsd-00001-00001 2021-12-06 13:43:16.421579 +0000 [ coolwsd ] ERR  Failed to unmount [/opt/cool/child-roots/X1XOTa7GEOp8hcxu]| common/JailUtil.cpp:70
wsd-00001-00001 2021-12-06 13:43:16.421776 +0000 [ coolwsd ] ERR  Failed to remove [/opt/cool/child-roots/X1XOTa7GEOp8hcxu] only: File not found| common/FileUtil.cpp:286
wsd-00001-00001 2021-12-06 13:43:16.424841 +0000 [ coolwsd ] ERR  Failed to unmount [/opt/cool/child-roots/cool_test_mount]| common/JailUtil.cpp:70
wsd-00001-00001 2021-12-06 13:43:16.429053 +0000 [ coolwsd ] ERR  Failed to unmount [/opt/cool/child-roots/]| common/JailUtil.cpp:70
wsd-00001-00001 2021-12-06 13:43:17.274715 +0000 [ coolwsd ] ERR  Failed to bind-mount [/opt/cool/systemplate] -> [/opt/cool/child-roots/cool_test_mount].| common/JailUtil.cpp:47
wsd-00001-00001 2021-12-06 13:43:17.274815 +0000 [ coolwsd ] ERR  Bind-Mounting fails and will be disabled for this run. To disable permanently set mount_jail_tree config entry in coolwsd.xml to false.| common/JailUtil.cpp:209
wsd-00001-00001 2021-12-06 13:43:18.078145 +0000 [ coolwsd ] ERR  Failed to open directory [/usr/bin/browser/welcome] (ENOENT: No such file or directory)| wsd/FileServer.cpp:737
wsd-00001-00001 2021-12-06 13:43:18.087250 +0000 [ coolwsd ] ERR  #18 Bind to location coolwsd-dQPQKUXA result - 0 (ENOENT: No such file or directory)| net/Socket.cpp:1005
`

**Comment by ElaaxMarketing** [comment]
![Screenshot from 2021-12-06 14-55-19](https://user-images.githubusercontent.com/84767639/144858707-80e1e9c4-239e-4b5e-8336-cf0efef0dd3b.png)
