### ISSUE TITLE
Regression CODE 21.11.1.1 Calc: "Add Comment" Will Edit a Random Comment

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#4045]
**Describe the bug**
Calc comments again - these are unfortunately usuable for me with CODE 21.11.1.1, but it seems to be document related again. :-/

Not sure what I'm doing to always trigger these problems.

For one important document, trying to add a new comment will usually start editing some already existing random comment. :-(

See the attached screencast for an example / demonstration.

Unfortunately, I cannot provide the test file as an attachment here due to potentially private data in there, but I already provided this file directly to Collabora - so if you still have it, you can use it to reliably reproduce this behaviour, and if you already deleted it, I can provide it again via direct mail.

**To Reproduce**
1. Open a calc sheet with the test document and scroll down somewhat
2. Click "Insert -> Comment" on a cell without a comment

**Expected behavior**
The comment edit popup will open next to the cell on which the action was invoked, and will show an empty edit text field.

**Actual behavior**
The comment edit popup opens in the window's top-left corner and shows some already existing comment from some other cell.

**Screenshots**
![CODE 21 11 1 1 Calc Add Comment Edits Random Comment](https://user-images.githubusercontent.com/26199042/150639639-3a7abf4a-ca74-42ab-90bf-6d495760928b.gif)

COOLWSD Version:
21.11.1.1
git hash: 
e487386
LOKit Version:
built on 
a great technology base
Collabora Office 21.06.12.1
git hash: 
45f56ee
Angeboten von:
 
Ubuntu 18.04.6 LTS
 
ef3ec9a0

**Comment by Ezinnem** [comment]
This issue seems to have been fixed with this patch  #4059 

It is no longer reproducible on COOLWSD 21.11.1.4 git hash:[ 535278f5](https://github.com/CollaboraOnline/online/commits/535278f5)


@gohrner, please can you check again?

**Comment by BigTwoProduction** [comment]
@Ezinnem, I can confirm can't reproducible with
Version COOLWSD :
21.11.1.4 git hash: 535278f
Versison LOKit :
Collabora Office 21.06.13.1 git hash: 89a98df
Servi par : Ubuntu 20.04.3 LTS 4d6f4edd

But still reproducible with the lastest docker images from https://hub.docker.com/r/collabora/code
Version COOLWSD :
21.11.1.4 git hash: 739da71
Versison LOKit :
Collabora Office 21.06.13.1 git hash: 242d275
Servi par : Ubuntu 18.04.6 LTS 0a61f89c

Best regards,
Jordan.

**Comment by gohrner** [comment]
I'm on:

>COOLWSD Version: 21.11.1.4
> git hash: 739da71

and in this version the problem / bug still occurs every time.

Is Version COOLWSD : 21.11.1.4, git hash: 535278f already available as Debian images, so I can rebuild my Docker image to test?

**Comment by BigTwoProduction** [comment]
Hello,

Yes, The fix for this was put into master 4 days ago. And lastest docker images on https://hub.docker.com/r/collabora/code is 6 days old. So if you rebuild your docker images on master normal "Add Comment" will be fix :)

Best Regards,
Jordan.

**Comment by gohrner** [comment]
> Yes, The fix for this was put into master 4 days ago. And lastest docker images on https://hub.docker.com/r/collabora/code is 6 days old. So if you rebuild your docker images on master normal "Add Comment" will be fix :)

I'm not building the binaries myself, I'm just building the Docker image based on the binaries the Dockerfile downloads.

Unfortunately, these don't seem to have been updated so far, i.e. after the Docker rebuild I end up with the same build hash as before. :-(

So I'll probably have to wait for the next point release before I can confirm if it works for me.

**Comment by Ezinnem** [comment]
@gohrner, please can you test again? This issue should be fine now.

**Comment by gohrner** [comment]
Yes, it's resolved in 21.11.2.2.
