### ISSUE TITLE
The button text not visible

### ISSUE THREAD

**Issue by snetAT** [CollaboraOnline/online#4592]
**Describe the bug**
The button text not visible

**To Reproduce**
1. Activate in Personal - Settings Accessibility - Dark Theme
2. Set true "Use theme from the integrator" in coolwsd.xml
3. Open a document and navigate to the view menu for example, and activate "toogle ruler" or other buttons that snap to it.

**Expected behavior**
The button text should be visible.

**Screenshots**
![Screenshot from 2022-04-10 11-37-06](https://user-images.githubusercontent.com/5556794/162615364-993276ab-45fc-44ad-829d-b5f0d3d568b8.png)

**Client details:**
 - OS: Linux, Windows
 - Browser Chrome / Firefox 
 - Version 23.03
 - Device: Desktop

## Server details

**Operating system**:
Linux

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
8.0 fpm

**Nextcloud version:**
23.03

**Version of the richdocuments app**
latest

**Version of Collabora Online**
21.11.3.6

**Comment by Andreas-Kainz** [comment]
Look like it's a NextCloud Office branding.css issue.

**Comment by Ornanovitch** [comment]
I have the same problem with nextcloud dark mode. The bg color is tanken from inline css:

```css
:root {
  ...
  --co-primary-light
  ...
}
```

But folks from nextcloud office told it was a COOL issue : 
- https://github.com/nextcloud/richdocuments/issues/2140+

**Comment by Ezinnem** [comment]
@eszkadev, @pedropintosilva

**Comment by timar** [comment]
See also #4382

**Comment by pedropintosilva** [comment]
@snetat I think this has been fixed, in this example I have set also a dark color  from within NC settings(see the active tab label) : 
![image](https://user-images.githubusercontent.com/65948705/166455938-8245f74f-f9c8-4174-9a6b-d373d6f97581.png)

**Comment by pedropintosilva** [comment]
^ tested on `master` and `distro/collabora/co-21-11`

**Comment by Ornanovitch** [comment]
Just upgraded to the latest release (21.11.4.2) and it didn't fix it :/

**Comment by janilowski** [comment]
The issue seems to persist on NC 24.0.2 and office 6.1.1 :p 
<img width="989" alt="image" src="https://user-images.githubusercontent.com/76809077/179509254-8bf3c62f-b681-4727-8bed-6495f8f15cf9.png">

Users of my instance also reported missing icons in this Calc menu, which is used to format cell borders.
<img width="366" alt="image" src="https://user-images.githubusercontent.com/76809077/179509810-00471889-b04a-43ab-93fb-0501ffe21869.png">

**Comment by Ornanovitch** [comment]
Still an issue on 22.05. How can we progress on the "is it a NC or a CODE issue" question?

**Comment by jancborchardt** [comment]
Yep, happening again as mentioned in the meeting. @pedropintosilva @juliushaertl where do we fix it? :)
![Uploading dark mode header.png…]()

**Comment by juliushaertl** [comment]
So the tricky bit is that we currently read out the css variables which we do only have available for either light or dark theme, so maybe we need to add some extra backend logic to expose the light colors for Collabora. For 25 we could make use of https://github.com/nextcloud/server/pull/33564 for that easily

**Comment by juliushaertl** [comment]
Relevant code bits are in https://github.com/nextcloud/richdocuments/blob/2c61f2eadd51653c778d866b1740aac43ae9c9ac/src/helpers/coolParameters.js#L47-L79

**Comment by janilowski** [comment]
> Resolved by @juliushaertl : [nextcloud/richdocuments#2550](https://github.com/nextcloud/richdocuments/pull/2550) partying_face

This has not been fully fixed, some icons are still missing
<img width="214" alt="grafik" src="https://user-images.githubusercontent.com/76809077/198877307-88623c00-7636-4b84-9458-941768303c44.png">

**Comment by Ornanovitch** [comment]
I'm not sure this is the same bug...

![2022-10-30-133135_327x219_scrot](https://user-images.githubusercontent.com/34077099/198878604-4b2cde2e-ff0a-455b-a9a6-6759f22e4f41.png)

**Comment by juliushaertl** [comment]
I cannot reproduce this with the latest release, so maybe you can try to upgrade to the latest CODE build and report a separate issue if it still occurs.

**Comment by Andreas-Kainz** [comment]
> I'm not sure this is the same bug...
> 
> ![2022-10-30-133135_327x219_scrot](https://user-images.githubusercontent.com/34077099/198878604-4b2cde2e-ff0a-455b-a9a6-6759f22e4f41.png)

I see the dark icons are missing and there has to be added an css rule. I will fix it asap.

**Comment by Andreas-Kainz** [comment]
There are plenty of DarkMode issues (papercuts). For better tracking it would be better to have for each DarkMode papercut a separate issue please.
