### ISSUE TITLE
Adding comments with accented characters doesn't work (é, è, ...)

### ISSUE THREAD

**Issue by netadm001** [CollaboraOnline/online#4732]
If you want to add a commentary on a file (writer, calc, etc...) whit collabora online CODE from package nextcloud, the commentary is not added, not saved.

**To Reproduce**
Create a profile with username Frédéric and check a file to add a commentary, --> comment not added
Modifie your username details profile from Frédéric to Frederic and check a file to add a commentary, --> comment added and you can save your file

I find this bug after many hours tests (sorry for my english)

**Desktop (please complete the following information)**
 - OS: Linux Mint
 - Firefox, Chrome
 - Last
![github001](https://user-images.githubusercontent.com/104864455/166552471-a0c5bc69-ed91-4934-a4c9-f4a455c741a3.png)

**Comment by pedropintosilva** [comment]
Thank @netadm001 so much for taking the time to test and report back to us! I'm on it trying to reproduce it myself

**Comment by pedropintosilva** [comment]
I'm actually not able to set the username with those characters I wonder how you were able..hm mmaybe some Nextcloud bug. When I try to type that name within the username field I get: 
![image](https://user-images.githubusercontent.com/65948705/166640693-d0f38be3-c077-4ee6-8dea-252faee642e5.png)

So I was forced to enter `Frederic` for the `username`. For the display name `Frédéric` worked. 
After creating the user and creating and opening a file with that user logged in I was able to insert comments. Here is a screenshot of a document saved with a comment:

![image](https://user-images.githubusercontent.com/65948705/166640808-c799d18c-7c4d-4db2-a248-80827e8b8691.png)

Maybe better to file the bug in the richdocuments side: https://github.com/nextcloud/richdocuments

**Comment by netadm001** [comment]
Hi, thanks for your response, I go to post this on the "richdocuments" side :-)

**Comment by pedropintosilva** [comment]
ok thanks @netadm001 , let me paste here the issue for future reference: https://github.com/nextcloud/richdocuments/issues/2196

**Comment by thebearon** [comment]
I managed to reproduce this with Built-in CODE server (21.11.402), so the bug seems to be related to proxy.php, as @timar suggested.
It's enough to add comments with accented characters.

**Comment by netadm001** [comment]
> I managed to reproduce this with Built-in CODE server (21.11.402), so the bug seems to be related to proxy.php, as @timar suggested.
> It's enough to add comments with accented characters.

Hi, ok thanks for your test, response and tracking for this issues.
If I understand good, the bug is confirmed.
If I can help for testing (solution, fix, or other) no problem for me.
Nice day

**Comment by shakeme** [comment]
Same here with german umlauts.
I'm also open for testing if you need.

**Comment by netadm001** [comment]
Today, after 2 updates from the 19.05.2022, the bug is already present for me. I'm waiting for a fix, but I think this is not prioritized at this time. I hope this is resolved this year :-)

**Comment by dagguh** [comment]
Still happens. Very frustrating, because it drops your whole comment.

**Comment by TobiasReich** [comment]
Sorry to report that in Collabora _22.5.502_ this is still an issue.
Adding a comment with Umlauts or accents (ÄÖÜ...) does not save the comment.

**Comment by ilicz** [comment]
Running the bundled version of Collabora office 22.05.5.2 in Nextcloud 24.0.6 I found impossible to save any comments containing ANY of acctented Czech characters ěščřžýáíéďťňúů (does not matter if upppercase or lowercase). 
Unfortunatelly this does not seem to be limited just to accented characters, I also tried to insert (directly from keyboard) EURO character € which did not saved as well.

I started to copy in characters from Windows Charmap application: **all pure ASCII** characters from the beginnign of the table seems to be fine: (U+0021 ... U+007E)
`!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_``abcdefghijklmnopqrstuvwxyz{|}~`

Starting with next character in line (non-breakable space (U+00A0), Inverted Exclamation mark (U+00A1)... ) no other character seems to be usable in comments field.

**Comment by ilicz** [comment]
I just tested with Online demo server configured instead of the built-in-package that the functionality seems to be working fine. Issue might be in the Nextcloud's build-in-package setup.

**Comment by vsandre** [comment]
The Bug is still existing with Nextcloud 25 and CODE 22.05.7.2 It is very anoying.
Existing Comments saved offline and uploaded to the cloud are displayed correctly

**Comment by TobiasReich** [comment]
Any news regarding this?

**Comment by netadm001** [comment]
Hi,
At this time, the bug still exist for me, and my installation is up to date.

**Comment by Object9050** [comment]
Umlaut characters are occasionally not shown correctly in the comments. Sometimes they are shown correctly though. Very strange... 

![Image](https://github.com/user-attachments/assets/43e0ca0e-dded-473a-8e45-985526e909ee)

**Comment by jazevedo-coll** [comment]
@Object9050 What version are you using?
