### ISSUE TITLE
iOS App: some labels are broken in the sidebar

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#5843]
**Describe the bug**
Some buttons in the sidebar have broken labels in the current TestFlight version.

**To Reproduce**
1. Open a writer document in the TestFlight iOS app
2. Open the sidebar

**Expected behavior**
The labels of each button should be readable.

**Actual behavior**
Some labels are broken.

**Screenshots**
![image](https://user-images.githubusercontent.com/1211300/218404082-62605795-e557-47e4-a02a-a8ecd11bce82.png)

**Tablet**
 - OS: iPadOS 15.6.1
 - Version: 22.05.202302092239

**Comment by plubius** [comment]
Update: I did a little debugging this afternoon and was able to trace the incoming misencoded strings in the sidebar to the POLLIN handler in [DocumentViewController userContentController:didReceiveScriptMessage:] which packages the incoming data and pushes it to JavaScript.

So, the next place I'll be looking at is in LOKit. The iOS app assumes the incoming data from LOKit are in UTF-8 format so it seems odd for the reencoding of strings to happen in LOKit but if I find recoding code, maybe I can link it back to some JavaScript global setting and then I can look for something we can control in WKWebView.

**Comment by plubius** [comment]
After many tedious hours of debugging, I have found the cause of the mangled non-ASCII characters: [CODocument send2JS:length:] receives valid UTF-8. For example, é (\u00e9) is encoded as two bytes: 0xc3 0xa9).

Then, the code replaces each byte that is >= 0x80 with literal '\x##' characters so the 2 bytes for an 'é' in the UTF-8 string are replaced with '\xc3\xa9' characters (8 characters).

@tml1024 added the >= 0x80 in commit 2b84a35fe803b14e15e0df954ebe1f18387078db but removing that conditional causes rendering in JavaScript to fail. So, obviously the characters need to be escaped for the JavaScript code to be able to parse it before sending it to [WebKit evaluateJavaScript:completionHandler:].

In this super [hacky debug patch](https://github.com/CollaboraOnline/online/files/10892287/iosappoutput.txt), and force the 0xc3 0xa9 combination of byes to be replaced with '\xe9' characters (4 characters), an 'é' is properly rendered by the JavaScript.

I am sure that I can compose UTF-8 strings into UTF-16 beforehand and then do the character replacement, but the question is how will that affect binary data? In commit 2b84a35fe803b14e15e0df954ebe1f18387078db, @tml1024 noted that "binary data is now pased through send2JS". So I think we need a way to differentiate between string and binary data. Otherwise, composing binary (png?) data into UTF-16 will likely mangle the image data.

Thoughts?

**Comment by plubius** [comment]
I think I found the solution: the JavaScript codes assumes that the data sent from the iOS app is text until the first newline, then it is image data after that. So, by only applying hex encoding of non-ASCII characters *after* the first newline appears to protect the image data without mangling the text.

Thoughts?

**Comment by tml1024** [comment]
I think that is how it was initially, yes, but then at some stage random binary data started appearing also before the newline. Or maybe that was because of some other bug or mistake and it has since been corrected.
 
You should realise that while Online has been developed during the last years, and there has been quite large changes in how messages are passed between the processes and between the server and client, for long times (like half a year) there have been no checks whether the iOS app still works at all. (If not tasked to do it, I am not doing it in my own time. I am way past having such an attitude...)

**Comment by plubius** [comment]
@tml1024 I think my current fix is at best a limited fix. I've seen more than a few JSON messages pass through send2JS() that have image data embedded within JSON so newline that delimits image data probably only applies to a subset of the images that are now passed through to JavaScript.

I have this feeling that [WKWebView evaluateJavaScript:completion] does some manipulation of the NSString passed to it so I tried replacing the hex encoding loop with base64 encoding the NSString. I had a some success putting the raw UTF-8 message into an NSData instance and then exporting from NSData to a base64 encoded string. It worked fine when I added an atob() in the JavaScript code. The only problem is that NSData doesn't "compose" the UTF-8 multibyte characters into a single UTF-16 character before encoding.

The good news was that the base64 approach didn't lead to corrupt image data. So when I get some time, I was thinking of putting the raw data into an NSString (to compose the multibyte UTF-8 characters) and then base64 encode the string. I suspect, however, that any composed image data won't be decomposed on the JavaScript side.

**Comment by plubius** [comment]
> > The good news was that the base64 approach didn't lead to corrupt image data. So when I get some time, I was thinking of putting the raw data into an NSString (to compose the multibyte UTF-8 characters) and then base64 encode the string. I suspect, however, that any composed image data won't be decomposed on the JavaScript side.
> 
> Well, looks like my limited fix only works for Latin extended characters and has no effect on higher Unicode ranges such as Greek, Russian, or Japanese. UTF-8 strings in these Unicode ranges are still corrupted with or without my patch.
> 
> I will check if these strings are valid UTF-8 in send2JS: and, if they are, I will look at base64 encoding of the UTF-16 string.

The good news, is that Greek, Russian, and Japanese are making it over to the JavaScript from iOS just fine.  With the [this debug patch](https://github.com/CollaboraOnline/online/files/10904108/console.log.diff.txt), the JavaScript strings are still proper UTF-8 strings when output to Safari's console log so the Greek, Russian, and Japanese bugs are a different, JavaScript bug.

As for the hex encoding on the iOS side: @tml1024 had some good insights. The current code, even with my fix, as well as the JavaScript code is designed for only "tile:" messages which are well structured. With the current Online and LibreOffice code, multiline JSON is now coming through and the "everything after a newline is raw image data" is no longer true.

I am thinking of only applying the hex encoding when the message begins with "tile:". Anyone know if there are others that following the "text + newline + image" rule?

**Comment by nikslor** [comment]
I can't say much about the message prefixes / protocols (maybe ask mmeeks who knows more about this?). But the bug seems fixed in 22.05.10 (22.5.202303070027).

So I think we can mark this as fixed and close it with the release?

**Comment by plubius** [comment]
I will close the bug. The current fix works, but it appears that there are still some cases where this bug will still occur. Where the bug will manifest once the string has been passed to JavaScript world, I do not know. Hence the need to filter on message types.

> I am thinking of only applying the hex encoding when the message begins with "tile:". Anyone know if there are other message prefixes that follow the "text + newline + image" rule?

Note for myself: potential list of message types to only apply the non-ASCII hex encoding to:

tile:
tilecombine:
delta:
renderfont:
rendersearchresult:
windowpaint:
