### ISSUE TITLE
Unable to adjust table size with cursor in documents #3229

### ISSUE THREAD

**Issue by GNU-Plus-Windows-User** [CollaboraOnline/online#7458]
### Describe the Bug

I'm unable to adjust the size of tables with my mouse in documents, it doesn't matter if it's a newly created document or old document. I haven't made any configuration changes to my server to cause this issue, it occured sometimes around the release of hub 5, I upgraded not long after to hub 5 and that's when the issue occured. I can consistently reproduce the issue on a fresh Nextcloud server with all the latest updates. I've tried stripping the CSP header to see if that was the cause of the issue since I noticed some CSP errors in the console log, I've tried switching to apache, and I've tried using different browsers (Firefox, Chrome) and even completely different OSs and machines (Ubuntu and Fedora Desktop).

### Steps to Reproduce

1. Create a document
2. Create a table
3. Try to adjust the table size with your mouse
4. The cursor will not change to indicate you can resize the table

### Expected Behavior

I should be able to adjust table width with my mouse

### Actual Behavior

I'm unable to adjust the size of a table, if I try to it just highlights parts of the table instead of resizing it.

### Screenshots

N/A

### Desktop

OS: Windows
Browser: Brave
Version: v1.59.117

### Smartphone

N/A

### Server details
**Operating system:**
Ubuntu 22.04
**Web server:**
Nginx 1.24.0
**Database:**
MariaDB 1.10.6
**PHP version:**
PHP 8.1
**Nextcloud version:**
Nextcloud 27.7.2 Hub 6
**Version of the richdocuments app**
8.2.0
**Version of Collabora Online**
23.05 non docker version installed from official repo

### Additional Context
Moved here from https://github.com/nextcloud/richdocuments/issues/3229

**browser log**
```

session heartbeat polling started
index.es.js:2337 Proxying an event bus of version 3.1.0 with 1.3.0
e @ index.es.js:2337
1099 @ index.es.js:3314
a @ bootstrap:19
6506 @ requesttoken.js:11
a @ bootstrap:19
3878 @ index.js:25
a @ bootstrap:19
395 @ index.js:14
a @ bootstrap:19
2534 @ index.js:41
a @ bootstrap:19
5391 @ notificationsService.js:67
a @ bootstrap:19
Promise.then (async)
NotificationsApp @ main.js:42
Do.d @ vue.runtime.esm.js:2796
Do @ vue.runtime.esm.js:4474
(anonymous) @ vue.runtime.esm.js:2916
hn @ vue.runtime.esm.js:2866
t.$createElement @ vue.runtime.esm.js:2639
render @ main.js:44
t._render @ vue.runtime.esm.js:2684
o @ vue.runtime.esm.js:3875
t.get @ vue.runtime.esm.js:3446
t @ vue.runtime.esm.js:3436
t @ vue.runtime.esm.js:3892
ir.$mount @ vue.runtime.esm.js:8772
t._init @ vue.runtime.esm.js:5701
ir @ vue.runtime.esm.js:5762
(anonymous) @ main.js:37
(anonymous) @ main.js:44
(anonymous) @ main.js:44
xhr.js:251 
        
        
       GET https://cloud.example.com/ocs/v2.php/apps/text/workspace?path=%2F 404 (Not Found)
(anonymous) @ xhr.js:251
xhr @ xhr.js:49
Ct @ dispatchRequest.js:51
request @ Axios.js:148
D.forEach.$t.<computed> @ Axios.js:174
(anonymous) @ bind.js:5
getFileInfo @ RichWorkspace.vue:144
mounted @ RichWorkspace.vue:106
xn @ vue.runtime.esm.js:3017
mr @ vue.runtime.esm.js:4031
t @ vue.runtime.esm.js:3905
ui.$mount @ vue.runtime.esm.js:8772
(anonymous) @ files.js:209
Promise.then (async)
render @ files.js:197
(anonymous) @ merged-index.js?v=7ad7ba1f-45:4665
setTimeout (async)
(anonymous) @ merged-index.js?v=7ad7ba1f-45:4664
initHeadersAndFooters @ merged-index.js?v=7ad7ba1f-45:4655
initialize @ merged-index.js?v=7ad7ba1f-45:4643
FileList @ merged-index.js?v=7ad7ba1f-45:4202
initialize @ merged-index.js?v=7ad7ba1f-45:82
(anonymous) @ merged-index.js?v=7ad7ba1f-45:406
(anonymous) @ delay.js:7
setTimeout (async)
(anonymous) @ delay.js:6
(anonymous) @ restArguments.js:18
Bt @ _executeBound.js:8
a @ partial.js:18
(anonymous) @ merged-index.js?v=7ad7ba1f-45:405
preview:1 
        
        
       GET https://cloud.example.com/core/preview?fileId=728086&x=250&y=250 404 (Not Found)
Image (async)
mounted @ RecommendedFile.vue:118
Ie @ vue.runtime.esm.js:3017
on @ vue.runtime.esm.js:4031
insert @ vue.runtime.esm.js:4423
S @ vue.runtime.esm.js:6942
(anonymous) @ vue.runtime.esm.js:7153
t._update @ vue.runtime.esm.js:3769
r @ vue.runtime.esm.js:3875
t.get @ vue.runtime.esm.js:3446
t.run @ vue.runtime.esm.js:3522
vn @ vue.runtime.esm.js:4121
(anonymous) @ vue.runtime.esm.js:3143
Le @ vue.runtime.esm.js:3065
Promise.then (async)
$e @ vue.runtime.esm.js:3090
Me @ vue.runtime.esm.js:3155
mn @ vue.runtime.esm.js:4207
t.update @ vue.runtime.esm.js:3513
t.notify @ vue.runtime.esm.js:720
set @ vue.runtime.esm.js:963
loading @ store.js:45
(anonymous) @ vuex.esm.js:844
(anonymous) @ vuex.esm.js:466
(anonymous) @ vuex.esm.js:465
Hi._withCommit @ vuex.esm.js:624
Hi.commit @ vuex.esm.js:464
Hi.commit @ vuex.esm.js:409
fetchRecommendations @ store.js:87
await in fetchRecommendations (async)
(anonymous) @ vuex.esm.js:851
Hi.dispatch @ vuex.esm.js:516
Hi.dispatch @ vuex.esm.js:406
render @ main.js:54
(anonymous) @ merged-index.js?v=7ad7ba1f-45:4665
setTimeout (async)
(anonymous) @ merged-index.js?v=7ad7ba1f-45:4664
initHeadersAndFooters @ merged-index.js?v=7ad7ba1f-45:4655
initialize @ merged-index.js?v=7ad7ba1f-45:4643
FileList @ merged-index.js?v=7ad7ba1f-45:4202
initialize @ merged-index.js?v=7ad7ba1f-45:82
(anonymous) @ merged-index.js?v=7ad7ba1f-45:406
(anonymous) @ delay.js:7
setTimeout (async)
(anonymous) @ delay.js:6
(anonymous) @ restArguments.js:18
Bt @ _executeBound.js:8
a @ partial.js:18
(anonymous) @ merged-index.js?v=7ad7ba1f-45:405
RecommendedFile.vue:116 could not load recommendation preview Event {isTrusted: true, type: 'error', target: img, currentTarget: img, eventPhase: 2, …}
e.onerror @ RecommendedFile.vue:116
error (async)
mounted @ RecommendedFile.vue:115
Ie @ vue.runtime.esm.js:3017
on @ vue.runtime.esm.js:4031
insert @ vue.runtime.esm.js:4423
S @ vue.runtime.esm.js:6942
(anonymous) @ vue.runtime.esm.js:7153
t._update @ vue.runtime.esm.js:3769
r @ vue.runtime.esm.js:3875
t.get @ vue.runtime.esm.js:3446
t.run @ vue.runtime.esm.js:3522
vn @ vue.runtime.esm.js:4121
(anonymous) @ vue.runtime.esm.js:3143
Le @ vue.runtime.esm.js:3065
Promise.then (async)
$e @ vue.runtime.esm.js:3090
Me @ vue.runtime.esm.js:3155
mn @ vue.runtime.esm.js:4207
t.update @ vue.runtime.esm.js:3513
t.notify @ vue.runtime.esm.js:720
set @ vue.runtime.esm.js:963
loading @ store.js:45
(anonymous) @ vuex.esm.js:844
(anonymous) @ vuex.esm.js:466
(anonymous) @ vuex.esm.js:465
Hi._withCommit @ vuex.esm.js:624
Hi.commit @ vuex.esm.js:464
Hi.commit @ vuex.esm.js:409
fetchRecommendations @ store.js:87
await in fetchRecommendations (async)
(anonymous) @ vuex.esm.js:851
Hi.dispatch @ vuex.esm.js:516
Hi.dispatch @ vuex.esm.js:406
render @ main.js:54
(anonymous) @ merged-index.js?v=7ad7ba1f-45:4665
setTimeout (async)
(anonymous) @ merged-index.js?v=7ad7ba1f-45:4664
initHeadersAndFooters @ merged-index.js?v=7ad7ba1f-45:4655
initialize @ merged-index.js?v=7ad7ba1f-45:4643
FileList @ merged-index.js?v=7ad7ba1f-45:4202
initialize @ merged-index.js?v=7ad7ba1f-45:82
(anonymous) @ merged-index.js?v=7ad7ba1f-45:406
(anonymous) @ delay.js:7
setTimeout (async)
(anonymous) @ delay.js:6
(anonymous) @ restArguments.js:18
Bt @ _executeBound.js:8
a @ partial.js:18
(anonymous) @ merged-index.js?v=7ad7ba1f-45:405
ServiceWorker.js:31 Refused to create a worker from 'https://cloud.example.com/index.php/apps/files/preview-service-worker.js' because it violates the following Content Security Policy directive: "script-src 'nonce-bk1GM3d0U3RmV3Z5Q05FcDFoL2Y0TW9uWTNCV1o3ek1PNW5nR09YbExqYz06cjRZT21QLzRLaVNLZWJvYXVtejBncWdWTWlrbUx0TDBkZUdNVDdPSVMxQT0='". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

(anonymous) @ ServiceWorker.js:31
load (async)
35766 @ ServiceWorker.js:28
r @ files-main.js?v=7ad7ba1f-45:2
(anonymous) @ files-main.js?v=7ad7ba1f-45:2
r.O @ chunk loaded:25
(anonymous) @ files-main.js?v=7ad7ba1f-45:2
(anonymous) @ files-main.js?v=7ad7ba1f-45:2
ConsoleLogger.js:59 [ERROR] files: SW registration failed:  {app: 'files', uid: 'redactedusername', level: 2, error: DOMException: Failed to register a ServiceWorker: The provided scriptURL ('https://cloud.example.c…}
value @ ConsoleLogger.js:59
value @ ConsoleLogger.js:85
(anonymous) @ ServiceWorker.js:34
load (async)
35766 @ ServiceWorker.js:28
r @ files-main.js?v=7ad7ba1f-45:2
(anonymous) @ files-main.js?v=7ad7ba1f-45:2
r.O @ chunk loaded:25
(anonymous) @ files-main.js?v=7ad7ba1f-45:2
(anonymous) @ files-main.js?v=7ad7ba1f-45:2
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'run-ad-auction'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'join-ad-interest-group'.
Error with Permissions-Policy header: Unrecognized feature: 'idle-detection'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.
bundle.js:30370 Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at NewClass.insertButtonToClassicToolbar (bundle.js:30370:67)
    at NewClass.insertCustomButton (bundle.js:30382:24)
    at NewClass.insertButton (bundle.js:30380:65)
    at NewClass._postMessageListener (bundle.js:23238:21)
    at handler (bundle.js:22037:35)
insertButtonToClassicToolbar @ bundle.js:30370
insertCustomButton @ bundle.js:30382
insertButton @ bundle.js:30380
_postMessageListener @ bundle.js:23238
handler @ bundle.js:22037
postMessage (async)
e.sendPostMessage @ postMessage.tsx:41
e.sendWOPIPostMessage @ postMessage.tsx:51
sendPostMessage @ Office.vue:264
documentReady @ Office.vue:270
postMessageHandler @ Office.vue:315
(anonymous) @ postMessage.tsx:91
e.handlePostMessage @ postMessage.tsx:85
(anonymous) @ postMessage.tsx:29
postMessage (async)
_postMessage @ bundle.js:23303
fire @ bundle.js:12104
_onMessage @ bundle.js:12309
_emitSlurpedEvents @ bundle.js:12206
(anonymous) @ bundle.js:12193
setTimeout (async)
_queueSlurpEventEmission @ bundle.js:12193
_slurpMessage @ bundle.js:12213
files/?dir=%2F&fileid=6:1 Autofocus processing was blocked because a document already has a focused element.
```

**Comment by Ezinnem** [comment]
I can reproduce this.

**Comment by GNU-Plus-Windows-User** [comment]
Thank you, let me know if you have a version I can test or if you have a workaround.

**Comment by timur-g** [comment]
Please add a scrrenshot and small screencast. 
I can adjust size . Adjusting works. just cursor seems to change only after using it, instead of when hovering. 
![image](https://github.com/CollaboraOnline/online/assets/7240617/70eb5dd4-7c20-4dfa-a8f0-93475bef195a)

**Comment by GNU-Plus-Windows-User** [comment]
I don't get the menu shown in your screenshot
looks like this for me (and yes, I selected the table)
![screenshot](https://github.com/CollaboraOnline/online/assets/115671214/8ff8cbdc-1ebe-43e8-9520-ca7cce9c3b78)

**Comment by timur-g** [comment]
To get the adjust points, you need to click in the table. This is screenshot from Firefox.
![image](https://github.com/CollaboraOnline/online/assets/7240617/50523e71-11a0-451f-8d50-3cacc1dbac6c)
Did you try with other browsers? It is not Windows browser issue.

**Comment by GNU-Plus-Windows-User** [comment]
I just updated my collabora online server to 23.05.5.2 yesterday and the issue is fixed
Thank you for the awesome work collabora team ❤️

**Comment by 2II3** [comment]
our server is updated to version: 24.04.5.2.1 
Problem still occurs. 
We use repro: https://github.com/nextcloud/all-in-one
