### ISSUE TITLE
F-Droid repo "null" problem

### ISSUE THREAD

**Issue by JohnVeness** [CollaboraOnline/online#9670]
### Describe the Bug
For about a week, refreshing F-Droid with the Collabora Office repo (https://www.collaboraoffice.com/downloads/fdroid/repo) enabled, gives an error saying "null".

### Steps to Reproduce
1. Run F-Droid
2. Make sure https://www.collaboraoffice.com/downloads/fdroid/repo is enabled
3. Refresh apps in F-Droid

### Expected Behavior
F-Droid refresh to happen without error.

### Actual Behavior
F-Droid says "Collabora Office F-Droid Repo: null. All other repos didn't create errors"

### Screenshots
![Screenshot_20240730_155644_F-Droid](https://github.com/user-attachments/assets/dac15139-9eea-4dda-b9c5-c20d991832ae)

### Smartphone
 - **Device:** Samsung Galaxy A54 5G
 - **OS:** Android 14 (One UI 6.1)

**Comment by Corbachini33** [comment]
Same issue on Oneplus 9, Android 14, Lineage OS 21

**Comment by Norde** [comment]
Same issue here.
Impossible to add the Collabora Office F-Droid repo or to update from it (despite that fact that we can access the files on the repo using a web browser)

**Comment by AxeldeWater** [comment]
Same issue here.

**Comment by timur-g** [comment]
Thanks for reporting. This should be fixed now. As you may see, there is 23.05 stable and 24.04 snapshot nearing a release.
Snapshot is updated once a week.

**Comment by hafeoz** [comment]
I'm still unable to add the repository using url https://www.collaboraoffice.com/downloads/fdroid/repo :
![org.fdroid.download.NotFoundException](https://github.com/user-attachments/assets/71694946-e776-4cab-bea0-037c9d193a51)

Is anyone else facing the same issue too?

**Comment by timur-g** [comment]
I can delete and add.

**Comment by hafeoz** [comment]
I've reinstalled F-Droid and it's working for me too. Probably some weird cache thing I guess.
