### ISSUE TITLE
#about-dialog too big 

### ISSUE THREAD

**Issue by jooooaah** [CollaboraOnline/online#9808]
**Describe the bug**
When opening an office document in Nextcloud via Nextcloud.Office-App, the credits beyond the footer are way too big, even if the credits should not be reduced in any way.  div #about-dialog beyond footer has 355px height - too much for small screen sizes an mobiles devices

**To Reproduce**
1. Open Nextcloud in browser
2. Open Office-Document (doesn't matter which type)

**Expected behavior**
Smaller credit line at the bottom page

**Screenshots**
![Firefox_Screenshot_2024-08-14T09-07-39 138Z](https://github.com/user-attachments/assets/8977ccce-2d99-4ae0-ade5-bad0e4b82097)

**Client details:**
 - OS: Win10, OpenSuse (Server on Ubuntu 22.04)
 - Browser: tested with Chromium and firefox
 - Device: [Android and desktop]

## Server details
Nextcloud Server: 28.0.6, and 29.0.3 RC2
NC Office App: 8.3.8, 8.3.9
Coolwsd 24.4.6.1 (via High Performace Backend)

**Operating system**:
Debian Bookworm

#### Browser log
```
Message should be filterd during slurp [bundle.js:17059:49](https://xxx.xx/collabora/browser/8ec5fda/bundle.js)
    _onMessage https://xxx.xx/collabora/browser/8ec5fda/bundle.js:17059
    _onMessage https://xxx.xx/collabora/browser/8ec5fda/bundle.js:10276
    _emitSlurpedEvents https://xxx.xx/collabora/browser/8ec5fda/bundle.js:10022
    _slurpTimer https://xxx.xx/collabora/browser/8ec5fda/bundle.js:10009
    (Async: setTimeout handler)
    _queueSlurpEventEmission https://xxx.xx/collabora/browser/8ec5fda/bundle.js:10008
    _slurpMessage https://xxx.xx/collabora/browser/8ec5fda/bundle.js:10034
    _emptyQueue https://xxx.xx/collabora/browser/8ec5fda/bundle.js:9941
    connect https://xxx.xx/collabora/browser/8ec5fda/bundle.js:9939
    loadDocument https://xxx.xx/collabora/browser/8ec5fda/bundle.js:11030
    <anonym> https://xxx.xx/collabora/browser/8ec5fda/bundle.js:34711
    <anonym> https://xxx.xx/collabora/browser/8ec5fda/bundle.js:34715
    <anonym> https://xxx.xx/collabora/browser/8ec5fda/bundle.js:34715

```

</details>

**Comment by Darshan-upadhyay1110** [comment]
hii @jooooaah thanks for reporting. We have already addressed this issue in **24.04.6.2**

COOLWSD version: **24.04.6.2** (git hash: 2efd1b47 (E))
LOKit version: Collabora Office 24.04.6.2 (git hash: 47680e0)
Served by: openSUSE Leap 15.5
Server ID: c8ff466a


Can you please update to 24.04.6.2 then will start to work fine again :)

Thanks,
Darshan

**Comment by Kieltux** [comment]
The issue is still there with 26.04.6.2

COOLWSD version: 24.04.6.2(git hash: 4fd2181(E))
LOKit version: Collabora Office 24.04.6.2 (git hash: 47680e0)
Served by: openSUSE Leap 15.5
Server ID: b9f8bff1

![grafik](https://github.com/user-attachments/assets/431bbdb9-f269-4fd0-b7b5-05faad058044)
